import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,tick,forecast,validate,catchUp,DAY_MS} from '../src/engine.js';import {usedMarket,leaseDaily,hubSlots} from '../src/expansion.js';import {loadSave,persistSave} from '../src/storage.js';
function rich(){const s=fresh();s.cash=1e9;s.xp=15000;s.founded=true;return s}
function route(s){act(s,'route',{plane:1,to:'HND',fare:200});return s.routes[0]}
test('v1 migration retains company, passengers, fleet, routes and finances exactly',()=>{const s=rich();route(s);tick(s);const old=structuredClone(s);for(const k of ['edition','hubs','hubLimits','facilities','loyalty','ancillary','totalCargo','cargo','challenge','fuelPrice','campaign','hedge','news','achievements','totalRevenue','totalCost','challengeCycle','usedBought','insurance','autoMaintain'])delete old[k];old.fleet.forEach(f=>{delete f.cabin;delete f.age;delete f.lease});old.routes.forEach(r=>{delete r.catering;delete r.frequency});const migrated=validate(old);for(const k of ['cash','debt','day','pax','flights','xp','name','claimed','staff'])assert.deepEqual(migrated[k],s[k]);assert.equal(migrated.routes[0].to,s.routes[0].to);assert.equal(migrated.fleet[0].id,s.fleet[0].id);assert.deepEqual(validate(migrated),migrated)});
test('new hubs support routes, survive import, and reject duplicate hubs',()=>{const s=rich();act(s,'open-hub',{hub:'SIN'});act(s,'route',{from:'SIN',plane:1,to:'BKK',fare:120});assert.equal(s.routes[0].from,'SIN');assert.deepEqual(validate(s),s);assert.throws(()=>act(s,'open-hub',{hub:'SIN'}));assert.equal(hubSlots(s,'SIN'),10);act(s,'facility',{hub:'SIN',id:'terminal'});assert.equal(hubSlots(s,'SIN'),18)});
test('leasing charges daily rent and cannot create sale profits',()=>{const s=rich();act(s,'lease',{model:'e195'});const f=s.fleet.at(-1);assert.equal(f.lease,true);assert.throws(()=>act(s,'sell',{id:f.id}),/租機/);const cash=s.cash;tick(s);assert.equal(s.cash,cash+s.history.at(-1).profit);assert.equal(s.history.at(-1).lease,leaseDaily(f));act(s,'return-lease',{id:f.id});assert.equal(s.fleet.length,1)});
test('used aircraft cannot be bought twice; renewal permits new deals',()=>{const s=rich(),d=usedMarket(s)[0];act(s,'used-buy',{id:d.id});assert.equal(s.fleet.at(-1).condition,d.condition);assert.throws(()=>act(s,'used-buy',{id:d.id}));s.day+=7;assert.notEqual(usedMarket(s)[0].id,d.id)});
test('cabin and catering changes are reflected in economics; frequency stays feasible',()=>{const s=rich(),r=route(s),before=forecast(s,r);act(s,'cabin',{id:1,cabin:'business'});assert.ok(forecast(s,r).capacity<before.capacity);assert.ok(forecast(s,r).averageFare>before.averageFare);act(s,'schedule',{id:r.id,frequency:12,catering:'premium'});assert.ok(forecast(s,r).rotations<=forecast(s,r).maxRotations);assert.throws(()=>act(s,'schedule',{id:r.id,frequency:-1,catering:'premium'}))});
test('cargo ships freight without passengers; high cargo rates reduce demand',()=>{const s=rich();act(s,'buy',{model:'b777f'});const id=s.fleet.at(-1).id;act(s,'route',{plane:id,to:'SIN',fare:250});const r=s.routes[0],e=forecast(s,r);assert.equal(e.pax,0);assert.ok(e.cargoTons>0&&e.cargoRevenue>0);r.fare=1500;assert.ok(forecast(s,r).cargoTons<e.cargoTons);const cash=s.cash;tick(s);assert.ok(s.totalCargo>0);assert.equal(s.cash,cash+s.history.at(-1).profit)});
test('automatic maintenance reconciles cost and preserves fleet reliability',()=>{const s=rich();route(s);s.fleet[0].condition=25;act(s,'auto-maintain');const cash=s.cash;tick(s);assert.ok(s.fleet[0].condition>99);assert.ok(s.history.at(-1).automaticMaintenance>0);assert.equal(s.cash,cash+s.history.at(-1).profit)});
test('hedge fixes fuel price and expires; campaign cannot stack indefinitely',()=>{const s=rich();route(s);act(s,'hedge');act(s,'campaign');assert.throws(()=>act(s,'campaign'));s.fuelPrice=1.6;const e=forecast(s,s.routes[0]);assert.equal(s.hedge.price,1);s.day=s.hedge.until;tick(s);assert.equal(s.hedge,null);assert.equal(s.campaign,null);assert.ok(forecast(s,s.routes[0]).fuel>e.fuel)});
test('challenge and achievements are rewarded at most once',()=>{const s=rich();s.day=6;tick(s);const c=s.challenge;s[c.metric]=c.start+c.target;act(s,'challenge-claim');assert.throws(()=>act(s,'challenge-claim'));act(s,'open-hub',{hub:'SIN'});act(s,'achievement',{id:'hub2'});assert.throws(()=>act(s,'achievement',{id:'hub2'}))});
class Store{constructor(){this.m=new Map()}getItem(k){return this.m.get(k)||null}setItem(k,v){this.m.set(k,v)}}
test('corrupt save cannot be replaced by fresh data, backup recovery preserves damaged original',()=>{const store=new Store();store.setItem('save','{bad');assert.equal(loadSave(store,'save',validate,fresh).state,null);assert.equal(store.getItem('save'),'{bad');const old=rich();delete old.edition;store.setItem('save-backup',JSON.stringify(old));const result=loadSave(store,'save',validate,fresh);assert.equal(result.recovered,true);assert.equal(store.getItem('save-damaged-original'),'{bad');assert.equal(store.getItem('save-pre-v2'),JSON.stringify(old));persistSave(store,'save',result.state);assert.equal(store.getItem('save-damaged-original'),'{bad')});
test('snapshot rotation keeps three recent days and leaves pinned migration backup intact',()=>{const store=new Store(),s=rich();store.setItem('save-pre-v2','original');for(let i=1;i<=5;i++){s.day=i;persistSave(store,'save',s)}const snapshots=JSON.parse(store.getItem('save-snapshots'));assert.deepEqual(snapshots.map(x=>x.day),[5,4,3]);assert.equal(store.getItem('save-pre-v2'),'original')});
test('thousands of days with hubs, leasing and freight stay serializable',()=>{const s=rich();route(s);act(s,'auto-maintain');act(s,'cargo-enable');act(s,'loyalty');act(s,'insurance');act(s,'lease',{model:'b777f'});act(s,'route',{plane:s.fleet.at(-1).id,to:'SIN',fare:230});for(let i=0;i<1000;i++){if(s.event)act(s,'event');tick(s)}assert.ok(Number.isFinite(s.cash));assert.ok(s.totalCargo>0);assert.deepEqual(validate(s),s)});
test('smart route optimization improves forecast without violating aircraft timing',()=>{const s=rich();act(s,'buy',{model:'atr'});act(s,'route',{plane:s.fleet.at(-1).id,to:'KHH',fare:50});const r=s.routes[0],before=forecast(s,r).profit;act(s,'optimize-route',{id:r.id});assert.ok(forecast(s,r).profit>=before);assert.ok(forecast(s,r).rotations<=forecast(s,r).maxRotations)});
test('unknown future save version is never downgraded to a previous backup',()=>{const store=new Store();store.setItem('save',JSON.stringify({...rich(),version:99}));store.setItem('save-backup',JSON.stringify(rich()));assert.equal(loadSave(store,'save',validate,fresh).state,null);assert.equal(JSON.parse(store.getItem('save')).version,99)});
test('used aircraft resale is bounded by acquisition cost to prevent immediate arbitrage',()=>{const s=rich(),cash=s.cash,d=usedMarket(s)[0];act(s,'used-buy',{id:d.id});const f=s.fleet.at(-1);act(s,'sell',{id:f.id});assert.ok(s.cash<cash)});
