import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,tick,forecast,distance,validate,catchUp,DAY_MS,level} from '../src/engine.js';
function company(){const s=fresh();act(s,'route',{plane:1,to:'HND',fare:200});return s}
test('geographic distance and starting route profitable',()=>{assert.ok(distance('TPE','HND')>2000&&distance('TPE','HND')<2300);const s=company(),e=forecast(s,s.routes[0]);assert.ok(e.profit>0);assert.ok(e.load>0&&e.load<=.98)});
test('higher fares reduce demand',()=>{const s=company(),r=s.routes[0],base=forecast(s,r);r.fare=600;assert.ok(forecast(s,r).pax<base.pax)});
test('range, duplicate, and aircraft assignment guards',()=>{const s=fresh();assert.throws(()=>act(s,'route',{plane:1,to:'LAX',fare:700}),/航程/);act(s,'route',{plane:1,to:'HND',fare:200});assert.throws(()=>act(s,'route',{plane:1,to:'KIX',fare:200}),/安排/)});
test('aircraft level and cash gates',()=>{const s=fresh();assert.throws(()=>act(s,'buy',{model:'a35k'}),/等級/);s.cash=0;assert.throws(()=>act(s,'buy',{model:'e195'}),/資金/)});
test('daily ledger reconciles and seeded results repeat',()=>{const a=company(),b=structuredClone(a),cash=a.cash;tick(a);tick(b);assert.deepEqual(a,b);const h=a.history.at(-1);assert.equal(a.cash,cash+h.revenue-h.cost);assert.ok(a.pax>0&&a.flights>0)});
test('maintenance grounds and restores flights',()=>{const s=company();s.fleet[0].condition=19;tick(s);assert.equal(s.flights,0);act(s,'maintain',{id:1});tick(s);assert.ok(s.flights>0);assert.ok(s.fleet[0].condition>99)});
test('loans cap and interest charged',()=>{const s=fresh();for(let i=0;i<5;i++)act(s,'loan');assert.throws(()=>act(s,'loan'),/上限/);tick(s);assert.ok(s.history.at(-1).cost>=8000);act(s,'repay');assert.equal(s.debt,8000000)});
test('milestone cannot be claimed twice',()=>{const s=company();tick(s);const cash=s.cash;act(s,'claim',{id:'first'});assert.equal(s.cash,cash+180000);assert.throws(()=>act(s,'claim',{id:'first'}))});
test('offline is bounded and paused games do not simulate',()=>{const s=company(),now=s.lastTick+DAY_MS*1000;assert.equal(catchUp(s,now),180);assert.equal(s.day,181);const day=s.day;s.active=false;catchUp(s,now+DAY_MS*50);assert.equal(s.day,day)});
test('save validation rejects corrupted or forged structure',()=>{const s=company();assert.deepEqual(validate(s),s);assert.throws(()=>validate({...s,cash:Infinity}));assert.throws(()=>validate({...s,version:99}));assert.throws(()=>validate({...s,research:{...s.research,fuel:200}}));assert.throws(()=>validate({...s,routes:[{...s.routes[0],to:'LAX'}]}))});
test('long simulation remains finite; resumes with maintenance',()=>{const s=company();for(let i=0;i<1500;i++){if(s.fleet[0].condition<40)act(s,'maintain',{id:1});if(s.event)act(s,'event',{accept:false});tick(s)}assert.ok(Number.isFinite(s.cash)&&s.cash>0);assert.ok(level(s)>=4);assert.equal(s.history.length,60);assert.ok(s.log.length<=35);validate(s)});
test('research changes operating cost and caps',()=>{const s=company();s.cash=1e9;const before=forecast(s,s.routes[0]).cost;for(let i=0;i<5;i++)act(s,'research',{id:'fuel'});assert.ok(forecast(s,s.routes[0]).cost<before);assert.throws(()=>act(s,'research',{id:'fuel'}))});
test('failed commands preserve all balances and routes',()=>{const s=fresh(),before=structuredClone(s);assert.throws(()=>act(s,'route',{plane:1,to:'HND',fare:'invalid'}));assert.deepEqual(s,before)});
test('repeatable contracts reward completed work and renew on expiry',()=>{const s=company();s.pax=6000;const c=s.cash;act(s,'contract');assert.ok(s.cash>c);assert.equal(s.cycle,2);assert.throws(()=>act(s,'contract'));s.day=s.contract.deadline;tick(s);assert.equal(s.contract.startPax,6000);assert.equal(s.contract.deadline,s.day+15)});
