import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {newFlight,step,STEP,aerodynamicCoefficients,rotate,integrateQuaternion,airframe,DESTINATION,flightResult} from '../src/flight/physics.js';
import {classifyDevice,autoQuality,PerformanceGovernor} from '../src/flight/adaptive.js';
import {gamepadInput} from '../src/flight/controls.js';
import {beginFlight,finishFlight,recoverInterruptedFlight} from '../src/flight/integration.js';
import {fresh,act,validate,tick,catchUp,VERSION} from '../src/engine.js';
import {persistSave,loadSave} from '../src/storage.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function departure(s,seconds=90){s.throttle=1;for(let i=0;i<seconds/STEP;i++){s.controls.pitch=s.telemetry.ias>135?clamp((10-s.telemetry.pitch)*.1,-1,1):0;step(s)}return s}
function landingPilot(s){const dist=Math.max(0,s.pos[2]-DESTINATION),desiredAlt=2.3+dist*.0524;const desiredVs=clamp((desiredAlt-s.pos[1])*.1-4,-6,2),desiredPitch=clamp((desiredVs-s.vel[1])*.7+3,-3,12);s.controls.pitch=clamp((desiredPitch-s.telemetry.pitch)*.1,-1,1);s.throttle=clamp(.45+(145-s.telemetry.ias)*.012,0,1);if(dist<120){s.throttle=0;s.controls.pitch=clamp((5-s.telemetry.pitch)*.1,-1,1)}s.brake=s.onGround;}
function company(){const s=fresh();s.founded=true;s.active=true;act(s,'route',{to:'HND',plane:1,fare:200});return s}
test('physical takeoff of all five airframes requires thrust, airspeed and lift',()=>{for(const model of ['e195','b738','b789','a359','a321']){const s=departure(newFlight({model}));assert.equal(s.status,'flying',model);assert.ok(s.pos[1]>50,model);assert.ok(s.takeoff);assert.ok(s.fuelUsed>0);assert.ok(s.telemetry.lift>0);assert.ok(s.telemetry.drag>0);assert.ok(s.telemetry.thrust>0)}const idle=newFlight();for(let i=0;i<1200;i++)step(idle);assert.equal(idle.pos[1],2.3);assert.ok(Math.abs(idle.pos[2]+180)<.1)});
test('fixed timestep is deterministic and quaternion remains normalized',()=>{const a=departure(newFlight()),b=departure(newFlight());assert.deepEqual(a,b);assert.ok(Math.abs(Math.hypot(...a.q)-1)<1e-10);let q=[0,0,0,1];for(let i=0;i<10000;i++)q=integrateQuaternion(q,[.1,.2,-.1],STEP);assert.ok(Math.abs(Math.hypot(...q)-1)<1e-10);assert.ok(Math.abs(Math.hypot(...rotate(q,[0,0,-1]))-1)<1e-10)});
test('stall reduces lift coefficient and increases drag; zero fuel removes thrust',()=>{const normal=aerodynamicCoefficients(.2),stall=aerodynamicCoefficients(.8);assert.ok(!normal.stall&&stall.stall);assert.ok(stall.cd>normal.cd);const s=newFlight({start:'approach'});s.fuel=0;s.throttle=1;step(s);assert.equal(s.telemetry.thrust,0)});
test('banking creates lateral acceleration and genuine heading change',()=>{const s=departure(newFlight(),60),x=s.pos[0];s.controls.pitch=0;s.controls.roll=.25;for(let i=0;i<1200;i++)step(s);assert.ok(s.telemetry.roll>5);assert.ok(Math.abs(s.pos[0]-x)>2);assert.ok(s.telemetry.heading>1&&s.telemetry.heading<359)});
test('stable approach, flare and braking can finish a real landing',()=>{const s=newFlight({start:'approach'});for(let i=0;i<240/STEP&&s.status==='flying';i++){landingPilot(s);step(s)}assert.equal(s.status,'landed');const r=flightResult(s);assert.equal(r.completed,true);assert.ok(r.score>50);assert.ok(s.touchdown.destination);assert.ok(s.touchdown.sink<4);assert.ok(Math.hypot(...s.vel)<8)});
test('gear-up, excessive sink and off-runway contact cause accidents',()=>{for(const setup of [s=>s.gear=false,s=>s.vel[1]=-10,s=>s.pos[0]=50]){const s=newFlight({start:'approach'});s.pos=[0,2.31,DESTINATION-200];s.vel=[0,-3,-70];setup(s);step(s);assert.equal(s.status,'crashed');assert.equal(flightResult(s).completed,false)}});
test('wind changes relative airspeed and deterministic turbulence changes forces',()=>{const a=newFlight({start:'approach'}),b=newFlight({start:'approach',weather:'wind'});step(a);step(b);assert.notEqual(a.telemetry.ias,b.telemetry.ias);const c=newFlight({start:'approach',weather:'storm'});for(let i=0;i<600;i++)step(c);assert.ok(Math.abs(c.pos[0])>1)});
test('adaptive UI combines viewport, touch and pointer; overrides are independent of quality',()=>{assert.equal(classifyDevice({width:390,height:844,touch:5,coarse:true}),'phone');assert.equal(classifyDevice({width:844,height:390,touch:5,coarse:true}),'phone');assert.equal(classifyDevice({width:1280,height:800,touch:5,coarse:true}),'tablet');assert.equal(classifyDevice({width:800,height:1280,touch:5,coarse:true}),'tablet');assert.equal(classifyDevice({width:1366,height:768,touch:0,coarse:false}),'desktop');assert.equal(classifyDevice({width:1280,height:800,touch:5},'desktop'),'desktop');assert.equal(autoQuality({mode:'desktop',cores:2,memory:2}),'low');assert.equal(autoQuality({mode:'tablet',cores:8,memory:8,dpr:1.5}),'medium')});
test('graphics governor lowers quality after sustained low FPS and respects cooldown',()=>{const g=new PerformanceGovernor('high');let change;for(let i=0;i<85;i++)change=g.sample(.05)||change;assert.equal(change.level,'medium');for(let i=0;i<30;i++)assert.equal(g.sample(.01),null)});
test('gamepad mapping, inversion and deadzone produce bounded control signals',()=>{const pad={axes:[.04,.6,-.5],buttons:Array.from({length:8},()=>({value:0,pressed:false}))};const c=gamepadInput(pad,{invertPitch:true});assert.equal(c.roll,0);assert.ok(c.pitch<0&&c.pitch>=-1);assert.ok(c.yaw<0);pad.buttons[7].value=1;assert.equal(gamepadInput(pad).throttleDelta,.3)});
test('SAS2 save validation preserves every original field without introducing flight defaults',()=>{const old=company();assert.deepEqual(validate(old),old);assert.equal(VERSION,1);const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};persistSave(storage,'skyline-save-v1',old);const raw=map.get('skyline-save-v1');assert.deepEqual(loadSave(storage,'skyline-save-v1',validate,fresh).state,old);assert.equal(map.get('skyline-save-v1'),raw);assert.equal(old.flightSession,undefined)});
test('flight freezes management, offline catchup and accelerated ticks without losing fields',()=>{const old=company(),before=structuredClone(old),s=beginFlight(old,old.routes[0].id,'flight-1',1000);assert.deepEqual(old,before);for(const key of ['cash','debt','pax','flights','fleet','routes','staff','research','claimed','history','day','nextId'])assert.deepEqual(s[key],old[key]);const day=s.day;tick(s);assert.equal(s.day,day);catchUp(s,1000000);assert.equal(s.day,day);const interrupted=recoverInterruptedFlight(s);assert.equal(interrupted.active,false);assert.equal(interrupted.flightSession.id,'flight-1')});
test('flight revenue settles once, journal reconciles, and replay is rejected without mutation',()=>{const old=company(),s=beginFlight(old,old.routes[0].id,'flight-2');const result={id:'flight-2',status:'landed',completed:true,score:90,sink:1,fuelUsed:200,duration:300,distance:18000,damage:.5};const done=finishFlight(s,result,{settle:true});assert.equal(done.flights,old.flights+1);const journal=done.flightJournal[0];assert.equal(done.cash-old.cash,journal.revenue-journal.cost);assert.equal(done.totalRevenue-old.totalRevenue,journal.revenue);assert.equal(done.totalCost-old.totalCost,journal.cost);assert.equal(done.fleet[0].condition,99.5);assert.equal(done.active,false);const raw=JSON.stringify(done);assert.throws(()=>finishFlight(done,result),/結算/);assert.equal(JSON.stringify(done),raw);assert.deepEqual(validate(done),done)});
test('practice result does not pay and malformed results or sessions cannot change company',()=>{const s=beginFlight(company(),2,'trial');const bad={id:'trial',status:'landed',completed:true,score:NaN,sink:0,fuelUsed:0,duration:30,distance:1000,damage:0};assert.throws(()=>finishFlight(s,bad,{settle:true}));const done=finishFlight(s,{...bad,status:'aborted',score:0,completed:false});assert.equal(done.cash,s.cash);assert.deepEqual(done.fleet,s.fleet);const broken=structuredClone(s);broken.flightSession.estimate.revenue=Infinity;assert.throws(()=>validate(broken),/飛行/)});
test('all redistributed aircraft are GLB2 with source originals, textures and GPL license',()=>{for(const name of ['e190','b738','b789','a359','a321']){const b=fs.readFileSync('public/assets/flight/'+name+'.glb');assert.equal(b.readUInt32LE(4),2);const json=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));assert.equal(json.asset.version,'2.0');assert.ok(json.meshes.length>0);assert.ok(json.materials.some(m=>m.pbrMetallicRoughness?.baseColorTexture));assert.ok(fs.existsSync('public/assets/flight/source/'+name+'.glb'))}assert.match(fs.readFileSync('public/assets/flight/COPYING','utf8'),/GNU GENERAL PUBLIC LICENSE/)});
test('CPU renderer projects visible 3D geometry and clips the near plane without changing simulation',async()=>{const T=await import('three'),{SoftwareRenderer}=await import('../src/flight/software-renderer.js');let fills=0;const coordinates=[];const ctx={fillRect(){},beginPath(){},moveTo(x,y){coordinates.push(x,y)},lineTo(x,y){coordinates.push(x,y)},closePath(){},fill(){fills++}};const canvas={getContext:()=>ctx},renderer=new SoftwareRenderer(canvas);renderer.setSize(800,600);const scene=new T.Scene();scene.background=new T.Color('#a8cde2');const mesh=new T.Mesh(new T.BoxGeometry(2,2,4),new T.MeshStandardMaterial({color:'#ffffff'}));mesh.position.z=-2;scene.add(mesh);const camera=new T.PerspectiveCamera(65,800/600,.5,100);const before=mesh.position.toArray();renderer.render(scene,camera);assert.ok(fills>0);assert.ok(coordinates.every(Number.isFinite));assert.deepEqual(mesh.position.toArray(),before);assert.equal(renderer.software,true);assert.equal(renderer.getContext(),null);renderer.dispose()});
test('crosswind and gusts do not amplify into an uncommanded roll or spin',()=>{for(const assist of [true,false])for(const weather of ['clear','wind','storm']){const s=newFlight({start:'approach',weather,assist});s.throttle=.6;let maxRoll=0,maxPitch=0,stallSeconds=0;for(let i=0;i<60/STEP;i++){step(s);maxRoll=Math.max(maxRoll,Math.abs(s.telemetry.roll));maxPitch=Math.max(maxPitch,Math.abs(s.telemetry.pitch));stallSeconds+=s.stall?STEP:0}assert.equal(s.status,'flying',`${weather}, assist=${assist}`);assert.ok(maxRoll<5);assert.ok(maxPitch<35);assert.equal(stallSeconds,0);if(weather==='clear')assert.equal(s.pos[0],0)}});
test('brief touch rotation then neutral input climbs without spurious stalls on all five aircraft',()=>{for(const model of ['e195','b738','b789','a359','a321'])for(const weather of ['clear','wind']){const s=newFlight({model,weather});s.throttle=1;let rotationStart,departedAt,stallSeconds=0;for(let i=0;i<90/STEP;i++){if(rotationStart===undefined&&s.telemetry.ias>140)rotationStart=s.t;s.controls.pitch=rotationStart!==undefined&&s.t-rotationStart<2?1:0;step(s);if(s.takeoff&&departedAt===undefined)departedAt=s.pos[2];stallSeconds+=s.stall?STEP:0;}assert.equal(s.status,'flying',model+' '+weather);assert.ok(departedAt>-3400);assert.ok(s.pos[1]>100);assert.equal(stallSeconds,0);assert.ok(Math.abs(s.telemetry.roll)<5)}});
test('stability aid recovers bank after stick release while manual controls remain available',()=>{const s=departure(newFlight(),60);s.controls.pitch=0;s.controls.roll=.7;for(let i=0;i<15/STEP;i++)step(s);assert.ok(s.telemetry.roll>15&&s.telemetry.roll<45);assert.ok(s.telemetry.heading>5&&s.telemetry.heading<90);s.controls.roll=0;for(let i=0;i<15/STEP;i++)step(s);assert.ok(Math.abs(s.telemetry.roll)<2);const manual=newFlight({start:'approach',assist:false});manual.controls.roll=.7;for(let i=0;i<5/STEP;i++)step(manual);assert.ok(manual.telemetry.roll>15)});
test('heading and ground orientation preserve right-turn direction at contact',()=>{const angle=30*Math.PI/180,s=newFlight();s.q=[0,-Math.sin(angle/2),0,Math.cos(angle/2)];step(s);assert.ok(Math.abs(s.telemetry.heading-30)<.01);const f=rotate(s.q,[0,0,-1]);assert.ok(f[0]>0);step(s);assert.ok(Math.abs(s.telemetry.heading-30)<.01)});
test('high angle of attack at high IAS still causes a physical stall even with assistance',()=>{const s=newFlight({start:'approach'});const angle=30*Math.PI/180;s.q=[Math.sin(angle/2),0,0,Math.cos(angle/2)];s.vel=[0,0,-100];step(s);assert.ok(s.telemetry.ias>180);assert.ok(s.telemetry.alpha>25);assert.equal(s.stall,true)});
