// SPDX-License-Identifier: GPL-2.0-or-later
import {clamp} from './physics.js';
export function gamepadInput(pad,{rollAxis=0,pitchAxis=1,yawAxis=2,invertPitch=false,deadzone=.08}={}){const axis=n=>{const v=pad.axes[n]||0;return Math.abs(v)<deadzone?0:clamp((Math.abs(v)-deadzone)/(1-deadzone),0,1)*Math.sign(v)};return {roll:axis(rollAxis),pitch:axis(pitchAxis)*(invertPitch?-1:1),yaw:axis(yawAxis),brake:!!pad.buttons[0]?.pressed,throttleDelta:((pad.buttons[7]?.value||0)-(pad.buttons[6]?.value||0))*.3}}
export function mountControls(root,s,settings,onAction){const keys=new Set(),touch={pitch:0,roll:0,yaw:0},abort=new AbortController(),opts={signal:abort.signal};let stickPointer=null,dragPointer=null,lastPadButtons=[];
const editing=e=>/INPUT|SELECT|TEXTAREA/.test(e.target?.tagName);
window.addEventListener('keydown',e=>{if(editing(e))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyS','KeyA','KeyD','KeyQ','KeyE','KeyG','KeyF','KeyC','KeyP','Escape','BracketLeft','BracketRight','Equal','Minus'].includes(e.code)){e.preventDefault();keys.add(e.code);if(!e.repeat){if(e.code==='KeyG')onAction('gear');if(e.code==='KeyF')onAction('flaps');if(e.code==='KeyC')onAction('camera');if(e.code==='KeyP')onAction('pause');if(e.code==='Escape')onAction('settings')}}},opts);
window.addEventListener('keyup',e=>keys.delete(e.code),opts);window.addEventListener('blur',()=>keys.clear(),opts);
const stick=root.querySelector('.virtual-stick'),knob=root.querySelector('.stick-knob');const stickMove=e=>{if(e.pointerId!==stickPointer)return;const r=stick.getBoundingClientRect(),radius=r.width*.34;touch.roll=clamp((e.clientX-r.left-r.width/2)/radius,-1,1);touch.pitch=clamp((e.clientY-r.top-r.height/2)/radius,-1,1);knob.style.transform=`translate(${touch.roll*radius}px,${touch.pitch*radius}px)`};stick.addEventListener('pointerdown',e=>{e.preventDefault();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e)},opts);stick.addEventListener('pointermove',stickMove,opts);const stickEnd=e=>{if(e.pointerId===stickPointer){stickPointer=null;touch.pitch=0;touch.roll=0;knob.style.transform=''}};stick.addEventListener('pointerup',stickEnd,opts);stick.addEventListener('pointercancel',stickEnd,opts);stick.addEventListener('lostpointercapture',stickEnd,opts);
root.querySelectorAll('[data-hold]').forEach(b=>{const set=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(b.dataset.hold==='brake')s.brake=true;else touch.yaw=Number(b.dataset.hold)};const reset=()=>{if(b.dataset.hold==='brake')s.brake=false;else touch.yaw=0};b.addEventListener('pointerdown',set,opts);b.addEventListener('pointerup',reset,opts);b.addEventListener('pointercancel',reset,opts);b.addEventListener('lostpointercapture',reset,opts)});
const throttle=root.querySelector('[name=throttle]');throttle.addEventListener('input',()=>s.throttle=Number(throttle.value)/100,opts);
// Mouse flight input is opt-in; dragging the clear viewport avoids pointer-lock requirements on iOS.
const view=root.querySelector('.flight-viewport');view.addEventListener('pointerdown',e=>{if(settings.mouse&&e.pointerType==='mouse'){dragPointer={id:e.pointerId,x:e.clientX,y:e.clientY};view.setPointerCapture(e.pointerId)}},opts);view.addEventListener('pointermove',e=>{if(dragPointer?.id===e.pointerId){touch.roll=clamp((e.clientX-dragPointer.x)/140,-1,1);touch.pitch=clamp((e.clientY-dragPointer.y)/140,-1,1)}},opts);const release=e=>{if(dragPointer?.id===e.pointerId){dragPointer=null;touch.pitch=touch.roll=0}};view.addEventListener('pointerup',release,opts);view.addEventListener('pointercancel',release,opts);
return {update(dt){let pitch=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0),roll=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),yaw=(keys.has('KeyE')?1:0)-(keys.has('KeyQ')?1:0);let padInput=null;const pad=navigator.getGamepads?.().find(Boolean);if(pad){padInput=gamepadInput(pad,{...settings,invertPitch:false});['gear','flaps','camera','pause'].forEach((a,i)=>{const pressed=pad.buttons[i+1]?.pressed;if(pressed&&!lastPadButtons[i])onAction(a);lastPadButtons[i]=pressed});s.throttle=clamp(s.throttle+padInput.throttleDelta*dt,0,1)}s.controls={pitch:clamp(pitch+touch.pitch+(padInput?.pitch||0),-1,1)*(settings.invertPitch?-1:1),roll:clamp(roll+touch.roll+(padInput?.roll||0),-1,1),yaw:clamp(yaw+touch.yaw+(padInput?.yaw||0),-1,1)};if(keys.has('Equal'))s.throttle=clamp(s.throttle+dt*.3,0,1);if(keys.has('Minus'))s.throttle=clamp(s.throttle-dt*.3,0,1);if(keys.has('BracketRight'))s.trim=clamp(s.trim+dt*.15,-.5,.5);if(keys.has('BracketLeft'))s.trim=clamp(s.trim-dt*.15,-.5,.5);s.brake=s.brake||keys.has('Space')||!!padInput?.brake;if(!keys.has('Space')&&!padInput?.brake&&!root.querySelector('[data-hold=brake]:active'))s.brake=false;if(document.activeElement!==throttle)throttle.value=Math.round(s.throttle*100)},clear(){keys.clear();touch.pitch=touch.roll=touch.yaw=0;s.controls={pitch:0,roll:0,yaw:0};s.brake=false;knob.style.transform=''},dispose(){abort.abort()}}}
