// SPDX-License-Identifier: GPL-2.0-or-later
// Fixed-step, SI units. Right-handed world: Y up, aircraft nose -Z.
export const STEP=1/120, G=9.80665, KT=1.943844, FT=3.28084;
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const dot=(a,b)=>a.reduce((n,v,i)=>n+v*b[i],0);
export const add=(a,b)=>a.map((v,i)=>v+b[i]);
export const mul=(a,n)=>a.map(v=>v*n);
export const norm=a=>Math.hypot(...a);
export const unit=a=>mul(a,1/(norm(a)||1));
export function rotate(q,v){const [x,y,z,w]=q,[a,b,c]=v,tx=2*(y*c-z*b),ty=2*(z*a-x*c),tz=2*(x*b-y*a);return [a+w*tx+y*tz-z*ty,b+w*ty+z*tx-x*tz,c+w*tz+x*ty-y*tx]}
export function integrateQuaternion(q,omega,dt){const [x,y,z,w]=q,[p,r,s]=omega,n=[x+(w*p+y*s-z*r)*dt/2,y+(w*r+z*p-x*s)*dt/2,z+(w*s+x*r-y*p)*dt/2,w+(-x*p-y*r-z*s)*dt/2];return mul(n,1/norm(n))}
export const AIRFRAMES={e195:{mass:45500,wing:92,length:41.5,span:35.1,thrust:166000,fuel:8500},b738:{mass:61000,wing:124.6,length:39.5,span:35.8,thrust:242000,fuel:15000},b789:{mass:175000,wing:325,length:62.8,span:60.1,thrust:570000,fuel:48000},a359:{mass:190000,wing:443,length:66.8,span:64.8,thrust:650000,fuel:55000},a321:{mass:72000,wing:128,length:44.5,span:35.8,thrust:294000,fuel:16000}};
export function airframe(id){return AIRFRAMES[id]||AIRFRAMES.e195}
export function groundOrientation(heading,pitch=0){const a=-heading/2,b=pitch/2;return [Math.cos(a)*Math.sin(b),Math.sin(a)*Math.cos(b),-Math.sin(a)*Math.sin(b),Math.cos(a)*Math.cos(b)]}
export const DESTINATION=-18000;
export function runwayAt(p){return Math.abs(p[0])<=30&&((p[2]<=0&&p[2]>=-3400)||(p[2]<=DESTINATION&&p[2]>=DESTINATION-3400))}
export function newFlight({model='e195',start='takeoff',weather='clear',time='day',id='practice'}={}){const a=airframe(model),approach=start==='approach';return {id,model,weather,time,t:0,pos:approach?[0,350,DESTINATION+6400]:[0,2.3,-180],vel:approach?[0,-3,-78]:[0,0,0],q:[0,0,0,1],omega:[0,0,0],throttle:approach?.42:0,engine:approach?.42:0,flaps:approach?2:1,gear:true,brake:false,trim:.08,fuel:a.fuel,fuelUsed:0,onGround:!approach,airborne:approach,takeoff:approach,touchdown:null,status:'flying',distance:0,maxAltitude:approach?350:2.3,maxG:1,stall:false,controls:{pitch:0,roll:0,yaw:0},wind:weather==='wind'?[5,0,2]:weather==='storm'?[9,0,5]:[0,0,0],telemetry:{ias:approach?78*KT:0,altitude:approach?350*FT:2.3*FT,pitch:0,roll:0,heading:0,vs:approach?-3*FT*60:0,alpha:0,lift:0,drag:0,thrust:0,g:1}}}
export function aerodynamicCoefficients(alpha,flaps=0,gear=false){const critical=(16+flaps*.7)*Math.PI/180,abs=Math.abs(alpha),stall=abs>critical;let cl=.22+4.8*alpha+.22*flaps;if(stall)cl*=clamp(1-(abs-critical)*2.6,.18,1);cl=clamp(cl,-1.3,1.65+.2*flaps);const cd=.024+.048*cl*cl+(gear?.024:0)+flaps*.015+(stall?(abs-critical)*.9:0);return {cl,cd,stall}}
export function step(s,dt=STEP){if(s.status!=='flying')return s;dt=clamp(dt,0,1/30);const a=airframe(s.model);s.t+=dt;const gust=s.weather==='storm'?[Math.sin(s.t*1.7)*2,Math.sin(s.t*2.1)*1.2,0]:[0,0,0];const wind=add(s.wind,gust),av=add(s.vel,mul(wind,-1)),speed=norm(av),forward=rotate(s.q,[0,0,-1]),up=rotate(s.q,[0,1,0]),right=rotate(s.q,[1,0,0]);const alpha=Math.atan2(-dot(av,up),Math.max(1,dot(av,forward))),beta=Math.atan2(dot(av,right),Math.max(1,dot(av,forward)));const rho=1.225*Math.exp(-Math.max(0,s.pos[1])/8500),dynamic=.5*rho*speed*speed;const coeff=aerodynamicCoefficients(alpha,s.flaps,s.gear);s.stall=coeff.stall&&speed>25&&!s.onGround;const lift=dynamic*a.wing*coeff.cl,drag=dynamic*a.wing*coeff.cd;
s.engine+=(s.throttle-s.engine)*Math.min(1,dt*.65);const burn=(.08+.85*s.engine)*a.thrust/166000*dt;if(s.fuel<=0)s.engine=0;const used=Math.min(s.fuel,burn);s.fuel-=used;s.fuelUsed+=used;const thrust=a.thrust*s.engine*Math.sqrt(rho/1.225)*(s.fuel>0?1:0),mass=a.mass+s.fuel*.2;
const liftDirection=unit(add(up,mul(unit(av),-dot(up,unit(av)))));let force=add(add(mul(forward,thrust),mul(unit(av),-drag)),mul(liftDirection,lift));force[1]-=mass*G;
const authority=clamp(dynamic/(.5*1.225*70*70),.05,2);const [pitchRate,yawRate,rollRate]=s.omega;
s.omega[0]+=(s.controls.pitch*.55+s.trim*.45-(alpha-.04)*.85-pitchRate*1.8)*authority*dt;
s.omega[1]+=(-s.controls.yaw*.35+beta*.65-yawRate*.9)*authority*dt;
s.omega[2]+=(-s.controls.roll*.9-rollRate*1.8-beta*.08)*authority*dt;
if(s.onGround){s.omega[0]=Math.max(0,s.omega[0]);s.omega[2]=0;const steering=-s.controls.yaw*.2*clamp(speed/8,0,1);s.omega[1]=steering;if(speed<45){s.omega[0]=0;s.q=integrateQuaternion([0,s.q[1],0,s.q[3]],[0,steering,0],dt)}const friction=(runwayAt(s.pos)?(s.brake?.43:.012):.10)*mass*G;const horizontal=unit([s.vel[0],0,s.vel[2]]);force=add(force,mul(horizontal,-Math.min(friction,norm(s.vel)*mass/Math.max(dt,.001))));if(force[1]<0)force[1]=0;}
s.q=integrateQuaternion(s.q,s.omega,dt);const old=[...s.pos];s.vel=add(s.vel,mul(force,dt/mass));s.pos=add(s.pos,mul(s.vel,dt));s.distance+=Math.hypot(s.pos[0]-old[0],s.pos[2]-old[2]);const f=rotate(s.q,[0,0,-1]),r=rotate(s.q,[1,0,0]),u=rotate(s.q,[0,1,0]);const pitch=Math.asin(clamp(f[1],-1,1)),roll=Math.atan2(r[1],u[1]);
if(s.pos[1]>3){s.onGround=false;s.airborne=true;s.takeoff=true;}if(s.pos[1]<=2.3){if(s.airborne&&!s.onGround){const sink=Math.max(0,-s.vel[1]),onRunway=runwayAt(s.pos),destination=s.pos[2]<=DESTINATION&&s.pos[2]>=DESTINATION-3400;s.touchdown={sink,roll:roll*180/Math.PI,pitch:pitch*180/Math.PI,speed,position:[...s.pos],onRunway,destination,time:s.t};if(!s.gear||sink>7||Math.abs(roll)>.32||pitch<-.1||pitch>.35||!onRunway)s.status='crashed';s.airborne=false;}s.pos[1]=2.3;s.vel[1]=0;s.onGround=true;s.omega[2]=0;const heading=Math.atan2(-f[0],-f[2]);if(s.takeoff){s.omega[0]=0;s.q=groundOrientation(heading,0)}else{s.q=groundOrientation(heading,clamp(pitch,0,.21));if(pitch>=.21)s.omega[0]=0;}if(s.touchdown?.destination&&s.status!=='crashed'&&speed<8)s.status='landed';}
if(s.pos[1]>13000||Math.abs(s.pos[0])>50000||s.pos[2]<-65000||s.pos[2]>25000||s.t>7200)s.status='aborted';
const g=lift/(mass*G);s.maxAltitude=Math.max(s.maxAltitude,s.pos[1]);s.maxG=Math.max(s.maxG,g);s.telemetry={ias:speed*Math.sqrt(rho/1.225)*KT,altitude:s.pos[1]*FT,pitch:pitch*180/Math.PI,roll:roll*180/Math.PI,heading:(Math.atan2(-f[0],-f[2])*180/Math.PI+360)%360,vs:s.vel[1]*FT*60,alpha:alpha*180/Math.PI,lift,drag,thrust,g};return s}
export function flightResult(s){const td=s.touchdown,landed=s.status==='landed'&&td?.destination;const score=landed?Math.round(clamp(100-td.sink*11-Math.abs(td.roll)*1.5-Math.abs(td.position[0])*.35,0,100)):0;return {id:s.id,status:s.status,completed:!!landed,score,sink:td?.sink||0,fuelUsed:s.fuelUsed,duration:s.t,distance:s.distance,maxAltitude:s.maxAltitude,damage:s.status==='crashed'?35:landed?clamp(.2+td.sink*.3,0,5):.1}}
