// SPDX-License-Identifier: GPL-2.0-or-later
import {newFlight,step,STEP,flightResult,DESTINATION,clamp} from './physics.js';
import {createScene} from './scene.js';
import {observeDevice,autoQuality,PerformanceGovernor} from './adaptive.js';
import {mountControls} from './controls.js';
const PREF='skyline-flight-settings-v1',SESSION='skyline-flight-session-v1';
const defaultSettings={ui:'auto',quality:'auto',invertPitch:false,mouse:false,deadzone:.08,rollAxis:0,pitchAxis:1,yawAxis:2};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function preferences(){try{return {...defaultSettings,...JSON.parse(localStorage.getItem(PREF)||'{}')}}catch{return {...defaultSettings}}}
export function savedFlight(id){try{const v=JSON.parse(localStorage.getItem(SESSION)||'null');if(v?.state?.id!==id)return null;const s=v.state;for(const a of [s.pos,s.vel,s.q,s.omega])if(!Array.isArray(a)||!a.every(Number.isFinite))return null;if(s.pos.length!==3||s.vel.length!==3||s.q.length!==4||s.omega.length!==3||!Number.isFinite(s.t)||s.t<0||s.t>7200||!Number.isFinite(s.fuel)||s.fuel<0||!Number.isFinite(s.fuelUsed)||Math.abs(Math.hypot(...s.q)-1)>.1)return null;return v}catch{return null}}
export async function startFlight({id,model='e195',start='takeoff',weather='clear',time='day',company='SKYLINE',color='#c6ed89',route='TRAINING SECTOR',settle=false,resume=false,onFinish}){
const settings=preferences(),saved=resume?savedFlight(id):null;let parkingBrake=false;let s=saved?.state||newFlight({id,model,start,weather,time}),paused=true,ended=false,disposed=false,contextLost=false,mode='chase',scene,device,quality='medium',governor=new PerformanceGovernor(),lastFrame=0,accumulator=0,hudTime=0,saveTime=0,fpsFrames=0,fpsTime=0,avgFps=0;
if(!document.querySelector('#flight-style')){const link=document.createElement('link');link.id='flight-style';link.rel='stylesheet';link.href='/flight.css';document.head.append(link)}
const root=document.createElement('section');root.className='flight-root';root.dataset.ui='desktop';root.setAttribute('aria-label','Flight Alpha 飛行模擬器');root.innerHTML=`<canvas class="flight-viewport" aria-label="3D 飛機、機場與跑道"></canvas><header class="flight-top"><div><span class="flight-brand">SKYLINE <b>FLIGHT ALPHA</b></span><small>${escape(company)} · ${escape(route)}</small></div><div class="flight-top-controls"><span class="device-badge">偵測裝置中</span><button data-flight="camera" aria-label="切換飛行視角">視角</button><button data-flight="pause" aria-label="暫停或繼續飛行">▶ 開始</button><button data-flight="settings" aria-label="飛行設定">⚙</button><button data-flight="exit" aria-label="結束本次飛行">離開</button></div></header><div class="flight-objective"><span class="objective-phase">PRE FLIGHT</span><strong class="objective-main">設定襟翼 1，油門 100%，空速 140 kt 後輕拉機頭</strong><small class="asset-status">載入飛機外觀…</small></div><div class="flight-alert" role="status"></div><div class="flight-hud"><div><small>IAS / KT</small><strong data-telemetry="ias">0</strong></div><div><small>ALT / FT</small><strong data-telemetry="altitude">8</strong></div><div><small>HDG / DEG</small><strong data-telemetry="heading">000</strong></div><div><small>VS / FPM</small><strong data-telemetry="vs">0</strong></div></div><div class="flight-instruments"><canvas class="pfd" width="300" height="260" aria-label="PFD 姿態、空速、高度儀表"></canvas><canvas class="nd" width="230" height="260" aria-label="ND 航向與目的跑道導航"></canvas><div class="engine-strip"><span>ENG <b class="engine-value">0%</b></span><span>FUEL <b class="fuel-value">0 kg</b></span><span>TRIM <b class="trim-value">0</b></span></div></div><div class="flight-stick"><span>ROLL / PITCH</span><div class="virtual-stick" role="application" aria-label="虛擬飛行搖桿：左右傾斜、下拉抬頭"><div class="stick-cross"></div><div class="stick-knob"></div></div><div class="rudder-controls"><button data-hold="-1" aria-label="左方向舵">◀</button><button data-hold="1" aria-label="右方向舵">▶</button></div></div><div class="flight-throttle"><label for="flight-throttle-input">THR <b class="throttle-value">0%</b></label><input id="flight-throttle-input" name="throttle" type="range" min="0" max="100" step="1" value="${s.throttle*100}" aria-label="飛行油門"><button data-hold="brake" class="brake-hold" aria-label="按住煞車">BRAKE</button></div><footer class="flight-bottom"><button data-flight="gear">GEAR <b class="gear-value">DOWN</b></button><button data-flight="flaps">FLAPS <b class="flaps-value">1</b></button><button data-flight="trim-down" aria-label="減少配平">TRIM −</button><button data-flight="trim-up" aria-label="增加配平">TRIM +</button><button data-flight="instruments">儀表</button><button data-flight="help">操作</button><span class="performance">— FPS</span></footer><div class="flight-dialog-layer" hidden></div>`;
document.body.append(root);document.body.classList.add('in-flight');const canvas=root.querySelector('.flight-viewport'),dialog=root.querySelector('.flight-dialog-layer');
const notify=message=>root.querySelector('.flight-alert').textContent=message;
function remember(){try{localStorage.setItem(PREF,JSON.stringify(settings));localStorage.setItem(SESSION,JSON.stringify({state:s,config:{id,model,start,weather,time,route,settle}}))}catch{notify('無法儲存飛行階段；航空公司原存檔保持不變。')}}
function setPaused(v){paused=v;controls?.clear();lastFrame=0;accumulator=0;root.querySelector('[data-flight=pause]').textContent=v?'▶ 繼續':'Ⅱ 暫停';remember()}
function overlay(title,content){dialog.hidden=false;dialog.innerHTML=`<section role="dialog" aria-modal="true" aria-label="${title}" class="flight-dialog"><h2>${title}</h2>${content}</section>`;dialog.querySelector('button,select,input')?.focus()}
function closeOverlay(){dialog.hidden=true;dialog.innerHTML=''}
function settingsDialog(){setPaused(true);overlay('飛行設定',`<div class="flight-setting-grid"><label>操作介面<select name="ui">${[['auto','自動偵測'],['phone','手機'],['tablet','平板'],['desktop','桌面']].map(([v,n])=>`<option value="${v}" ${settings.ui===v?'selected':''}>${n}</option>`).join('')}</select></label><label>3D 畫質<select name="quality">${['auto','low','medium','high'].map(v=>`<option value="${v}" ${settings.quality===v?'selected':''}>${v.toUpperCase()}</option>`).join('')}</select></label><label>反轉俯仰<input name="invertPitch" type="checkbox" ${settings.invertPitch?'checked':''}></label><label>滑鼠拖曳操控<input name="mouse" type="checkbox" ${settings.mouse?'checked':''}></label><label>控制器死區<input name="deadzone" type="number" min="0" max="0.4" step="0.01" value="${settings.deadzone}"></label>${[['rollAxis','橫滾軸'],['pitchAxis','俯仰軸'],['yawAxis','方向舵軸']].map(([k,n])=>`<label>${n}<input name="${k}" type="number" min="0" max="7" value="${settings[k]}"></label>`).join('')}</div><p>UI 與畫質各自獨立。自動畫質根據實際 FPS 調整。機場為 Alpha 原創訓練場景，不是全球實景。</p><button data-flight="apply-settings">儲存設定</button><button data-flight="close-dialog">返回飛行</button>`)}
function help(){setPaused(true);overlay('駕駛指南',`<p><b>起飛：</b>襟翼 1、油門 100%；IAS 約 140 kt，輕拉搖桿或按 S / ↓ 抬頭至 8–12°。離地後 G 收起落架，180 kt 後 F 收襟翼。</p><p><b>巡航：</b>配平與油門調整可維持高度；A/D 或 ←/→ 傾斜轉彎，Q/E 控制方向舵。+ / − 改油門，[ / ] 配平。</p><p><b>降落：</b>沿 ND 導引至 18 km 訓練目的跑道，約 3° 下滑。Gear DOWN、Flaps 2–3，IAS 135–155 kt，接地前減油門輕抬頭，Space 或按住 BRAKE 煞停。</p><p><b>Gamepad：</b>左搖桿飛行、右橫軸方向舵、扳機改油門；A 煞車、B 起落架、X 襟翼、Y 視角。可自訂軸、死區與反轉。觸控可同時操作搖桿、油門及煞車。</p><p>P 暫停、C 切換視角。碰撞與失速真的影響飛行。這是簡化空氣動力 Alpha，尚無 FMS、ILS 或自動駕駛。</p><button data-flight="close-dialog">返回飛行</button>`)}
async function endFlight(aborted=false){if(ended)return;setPaused(true);if(aborted&&s.status==='flying')s.status='aborted';const result=flightResult(s);overlay('航班結果',`<span class="result-score">${result.score}<small>/ 100</small></span><h3>${result.completed?'降落完成':result.status==='crashed'?'飛行事故':'訓練結束'}</h3><div class="flight-result-grid"><div>沉降率<strong>${result.sink.toFixed(2)} m/s</strong></div><div>燃油消耗<strong>${result.fuelUsed.toFixed(1)} kg</strong></div><div>飛行時間<strong>${Math.round(result.duration)} 秒</strong></div><div>航程<strong>${(result.distance/1000).toFixed(1)} km</strong></div></div><p>${settle?'完成後依飛行評分結算一架次收入及成本，使用一次性航班 ID；事故與中止不發收入。':'自由訓練不更動航空公司金錢或機況。'}</p><button data-flight="finish">完成並返回</button>`)}
function handle(action){if(action==='camera'){mode=['chase','cockpit','wing','tower'][(['chase','cockpit','wing','tower'].indexOf(mode)+1)%4];root.querySelector('[data-flight=camera]').textContent={chase:'追蹤',cockpit:'駕駛艙',wing:'機翼',tower:'觀察'}[mode]}else if(action==='pause'){if(!dialog.hidden)return;setPaused(!paused)}else if(action==='gear'){s.gear=!s.gear}else if(action==='flaps'){s.flaps=(s.flaps+1)%4}else if(action==='brake'){parkingBrake=!parkingBrake}else if(action==='trim-up'){s.trim=clamp(s.trim+.025,-.5,.5)}else if(action==='trim-down'){s.trim=clamp(s.trim-.025,-.5,.5)}else if(action==='instruments'){root.classList.toggle('instruments-collapsed')}else if(action==='settings')settingsDialog();else if(action==='help')help();else if(action==='exit'){setPaused(true);overlay('結束這次飛行？',`<p>中止航班不會發放收入。${settle?'本次航班已消耗的成本與機況將記錄。':'訓練不會修改公司資料。'}</p><button data-flight="abort">中止並查看結果</button><button data-flight="close-dialog">繼續飛行</button>`)}else if(action==='abort')endFlight(true);else if(action==='finish'){if(ended)return;try{onFinish(flightResult(s));ended=true;try{localStorage.removeItem(SESSION)}catch{}dispose()}catch(e){notify('結果未能儲存：'+e.message+'，請重試。')}}else if(action==='close-dialog'){closeOverlay();if(!contextLost)setPaused(false)}else if(action==='apply-settings'){settings.ui=dialog.querySelector('[name=ui]').value;settings.quality=dialog.querySelector('[name=quality]').value;settings.invertPitch=dialog.querySelector('[name=invertPitch]').checked;settings.mouse=dialog.querySelector('[name=mouse]').checked;settings.deadzone=clamp(Number(dialog.querySelector('[name=deadzone]').value)||0,0,.4);['rollAxis','pitchAxis','yawAxis'].forEach(k=>settings[k]=Math.round(clamp(Number(dialog.querySelector(`[name=${k}]`).value)||0,0,7)));deviceObserver.refresh();applyQuality(settings.quality==='auto'?autoQuality(device):settings.quality);remember();closeOverlay();setPaused(false)}else if(action==='restore-context'){rendererRestore()} }
const abort=new AbortController();root.addEventListener('click',e=>{const b=e.target.closest('[data-flight]');if(b)handle(b.dataset.flight)}, {signal:abort.signal});
let controls=mountControls(root,s,settings,handle);canvas.addEventListener('click',e=>{if(mode!=='cockpit'||!scene)return;const r=canvas.getBoundingClientRect(),picked=scene.pick((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));if(picked)handle(picked)},{signal:abort.signal});
const deviceObserver=observeDevice(root,settings,d=>{device=d;root.dataset.ui=d.mode;root.dataset.orientation=d.orientation;root.dataset.input=d.input;root.classList.toggle('reduced-motion',d.reduced);root.querySelector('.device-badge').textContent=`${{phone:'手機',tablet:'平板',desktop:'桌面'}[d.mode]} · ${d.gamepad?'控制器':d.input==='keyboard'?'鍵盤':d.input==='mouse'?'滑鼠':'觸控'}`;if(scene)scene.resize(d.width,d.height)});
function applyQuality(v){quality=v;governor=new PerformanceGovernor(v);scene?.setQuality(v);if(device)scene?.resize(device.width,device.height)}
const lost=e=>{e.preventDefault();contextLost=true;setPaused(true);overlay('圖形暫停',`<p>WebGL Context Lost。飛行已暫停，航空公司存檔與本次飛行階段保留。</p><button data-flight="restore-context">嘗試恢復圖形</button>`)};function rendererRestore(){const gl=scene?.renderer.getContext(),ext=gl?.getExtension('WEBGL_lose_context');if(ext)ext.restoreContext();else notify('請重新整理此 Preview，再選擇恢復飛行。')};const restored=()=>{contextLost=false;applyQuality(quality);closeOverlay();notify('圖形已恢復，按繼續飛行。')};canvas.addEventListener('webglcontextlost',lost);canvas.addEventListener('webglcontextrestored',restored);
quality=settings.quality==='auto'?autoQuality(device):settings.quality;
try{scene=await createScene(canvas,s,{quality,color,onAsset:label=>{if(!disposed)root.querySelector('.asset-status').textContent=label}});if(disposed){scene.dispose();return}scene.resize(device.width,device.height);governor=new PerformanceGovernor(quality)}catch(e){overlay('3D 無法啟動',`<p>此瀏覽器無法建立 WebGL2 或軟體繪圖。請改用支援繪圖的瀏覽器。航空公司資料仍保留。</p><button data-flight="abort">返回</button>`);return {dispose}}
function instruments(){const t=s.telemetry,pfd=root.querySelector('.pfd'),ctx=pfd.getContext('2d'),w=300,h=260;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0c1a20';ctx.fillRect(0,0,w,h);ctx.save();ctx.beginPath();ctx.rect(50,30,200,160);ctx.clip();ctx.translate(150,110);ctx.rotate(-t.roll*Math.PI/180);const pitch=t.pitch*2;ctx.fillStyle='#398bab';ctx.fillRect(-400,-400+pitch,800,400);ctx.fillStyle='#88705b';ctx.fillRect(-400,pitch,800,400);ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-400,pitch);ctx.lineTo(400,pitch);ctx.stroke();ctx.font='11px monospace';ctx.textAlign='center';for(let i=-30;i<=30;i+=5){if(!i)continue;const y=pitch-i*2;ctx.beginPath();ctx.moveTo(i%10?-18:-35,y);ctx.lineTo(i%10?18:35,y);ctx.stroke();if(i%10===0)ctx.fillText(Math.abs(i),48,y+4)}ctx.restore();ctx.strokeStyle='#d7f59a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(90,110);ctx.lineTo(132,110);ctx.lineTo(138,116);ctx.moveTo(162,116);ctx.lineTo(168,110);ctx.lineTo(210,110);ctx.stroke();ctx.fillStyle='#a5d9b3';ctx.textAlign='center';ctx.font='bold 16px monospace';ctx.fillText(String(Math.round(t.heading)).padStart(3,'0')+'°',150,22);ctx.fillStyle='#e4ede9';ctx.fillRect(4,96,43,30);ctx.fillRect(252,96,46,30);ctx.fillStyle='#111d20';ctx.font='bold 16px monospace';ctx.fillText(Math.round(t.ias),25,117);ctx.fillText(Math.round(t.altitude),275,117);ctx.fillStyle='#b0c6c8';ctx.font='11px monospace';ctx.fillText('IAS kt',25,145);ctx.fillText('ALT ft',275,145);ctx.fillText('VS '+Math.round(t.vs)+' fpm',150,211);ctx.fillText('BANK '+t.roll.toFixed(0)+'°   PITCH '+t.pitch.toFixed(0)+'°',150,235);
const nd=root.querySelector('.nd'),nc=nd.getContext('2d');nc.clearRect(0,0,230,260);nc.fillStyle='#0c1a20';nc.fillRect(0,0,230,260);nc.strokeStyle='#698a90';for(const radius of [45,85]){nc.beginPath();nc.arc(115,125,radius,0,Math.PI*2);nc.stroke()}nc.fillStyle='#b6cacc';nc.font='12px monospace';nc.textAlign='center';nc.fillText('N',115,27);nc.fillText('W',16,128);nc.fillText('E',215,128);nc.save();nc.translate(115,125);nc.rotate(-t.heading*Math.PI/180);nc.strokeStyle='#c6ed89';nc.lineWidth=2;nc.beginPath();nc.moveTo(-6,0);nc.lineTo(0,-13);nc.lineTo(6,0);nc.lineTo(0,-3);nc.closePath();nc.stroke();nc.restore();const dx=-s.pos[0],dz=DESTINATION-s.pos[2],dist=Math.hypot(dx,dz);nc.fillStyle='#b1e8f4';nc.beginPath();nc.arc(115+dx/Math.max(dist,1)*65,125+dz/Math.max(dist,1)*65,4,0,Math.PI*2);nc.fill();nc.fillStyle='#eef4ed';nc.fillText('ARR '+(dist/1000).toFixed(1)+' km',115,229);nc.fillText('GS '+(Math.atan2(Math.max(0,s.pos[1]-2.3),Math.max(1,dist))*180/Math.PI).toFixed(1)+'° · XTK '+s.pos[0].toFixed(0)+'m',115,249);}
function updateHUD(){const t=s.telemetry;for(const k of ['ias','altitude','heading','vs'])root.querySelector(`[data-telemetry=${k}]`).textContent=k==='heading'?String(Math.round(t[k])).padStart(3,'0'):Math.round(t[k]).toLocaleString();root.querySelector('.engine-value').textContent=Math.round(s.engine*100)+'%';root.querySelector('.fuel-value').textContent=Math.round(s.fuel)+' kg';root.querySelector('.trim-value').textContent=s.trim.toFixed(2);root.querySelector('.throttle-value').textContent=Math.round(s.throttle*100)+'%';root.querySelector('.gear-value').textContent=s.gear?'DOWN':'UP';root.querySelector('.flaps-value').textContent=s.flaps;root.querySelector('.performance').textContent=`${avgFps.toFixed(0)} FPS · ${quality.toUpperCase()}`;const dist=Math.hypot(s.pos[0],DESTINATION-s.pos[2]);root.querySelector('.objective-phase').textContent=paused?'PAUSED':s.onGround?s.takeoff?'ROLLOUT':'TAKEOFF':dist<6500?'APPROACH':'CLIMB / CRUISE';root.querySelector('.objective-main').textContent=s.onGround?(s.takeoff?'保持跑道中心線，油門 0%，按住 BRAKE 至完全停止':'襟翼 1 · 油門 100% · 約 140 kt 後輕拉至 8–12°'):dist<6500?'目的跑道 '+(dist/1000).toFixed(1)+' km · 襟翼 2–3 / 起落架 DOWN / 135–155 kt':'訓練目的跑道 '+(dist/1000).toFixed(1)+' km · 油門與配平控制高度';notify(s.stall?'STALL · 減小仰角，增加推力':!s.gear&&s.pos[1]<100?'GEAR WARNING · 起落架未放下':s.fuel<500?'LOW FUEL':paused?'飛行暫停 · 經營時間已凍結':'');instruments()}
function frame(now){if(disposed)return;requestAnimationFrame(frame);const dt=lastFrame?clamp((now-lastFrame)/1000,0,.15):0;lastFrame=now;if(!paused&&!contextLost&&!document.hidden&&s.status==='flying'){controls.update(dt);s.brake=s.brake||parkingBrake;accumulator+=dt;let n=0;while(accumulator>=STEP&&n<18){step(s,STEP);accumulator-=STEP;n++}if(s.status!=='flying')endFlight()}if(!contextLost){scene.draw(mode,device?.reduced?.04:dt);fpsFrames++;fpsTime+=dt;if(fpsTime>1){avgFps=fpsFrames/fpsTime;fpsTime=0;fpsFrames=0}if(settings.quality==='auto'&&!paused&&dt>0){const change=governor.sample(dt);if(change){quality=change.level;scene.setQuality(quality);scene.resize(device.width,device.height)}}}hudTime+=dt;saveTime+=dt;if(hudTime>.1||dt===0){hudTime=0;updateHUD()}if(saveTime>5){saveTime=0;remember()}}
const visibility=()=>{if(document.hidden)setPaused(true)};document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',remember);
function dispose(){if(disposed)return;disposed=true;controls.dispose();deviceObserver.dispose();abort.abort();document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pagehide',remember);canvas.removeEventListener('webglcontextlost',lost);canvas.removeEventListener('webglcontextrestored',restored);scene?.dispose();root.remove();document.body.classList.remove('in-flight')}
remember();updateHUD();overlay('準備駕駛',`<span class="flight-eyebrow">FLIGHT REVOLUTION / ALPHA 0.1</span><h3>${start==='approach'?'最後進場 · 6.4 km':'從跑道起飛 · 18 km 訓練航段'}</h3><p>訓練場景壓縮航程，具有真實受力與接地判定。${settle?'這班使用你的機隊及航線；經營時間已暫停。':'自由訓練不改動航空公司資料。'}</p><p>觸控：下拉搖桿抬頭，左右傾斜。右側滑桿控制油門。電腦：W/S 或 ↑/↓、A/D 或 ←/→，+ / − 油門。接地後按住 BRAKE。</p><button data-flight="close-dialog">開始飛行</button><button data-flight="help">完整操作說明</button>`);requestAnimationFrame(frame);return {dispose,state:s};}
