// SPDX-License-Identifier: GPL-2.0-or-later
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {airframe,DESTINATION,rotate} from './physics.js';
import {ASSETS} from './assets.js';
import {QUALITY} from './adaptive.js';
import {SoftwareRenderer} from './software-renderer.js';
export async function createScene(canvas,s,{quality='medium',color='#c6ed89',onAsset=()=>{}}={}){let disposed=false,renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'})}catch{renderer=new SoftwareRenderer(canvas)}renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=s.time==='night'?.65:1.1;const scene=new T.Scene(),night=s.time==='night',sunset=s.time==='sunset';scene.background=new T.Color(night?'#101e37':sunset?'#b69ba5':'#a8cde2');scene.fog=new T.Fog(scene.background,quality==='low'?5000:9000,QUALITY[quality].distance);const camera=new T.PerspectiveCamera(65,1,.5,QUALITY[quality].distance),hemi=new T.HemisphereLight(night?'#7d91bd':'#d9ecff','#64735b',night?.9:2);scene.add(hemi);const sun=new T.DirectionalLight(sunset?'#ffc090':'#fff4df',night?.3:3);sun.position.set(-800,1500,500);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-100;sun.shadow.camera.right=100;sun.shadow.camera.top=100;sun.shadow.camera.bottom=-100;sun.shadow.camera.near=1;sun.shadow.camera.far=4000;scene.add(sun,sun.target);
const mat=(c,roughness=.85)=>new T.MeshStandardMaterial({color:c,roughness});const grass=mat(night?'#23372e':'#678570'),asphalt=mat('#383e44'),concrete=mat('#8d989a'),white=mat('#f5efe0'),glass=mat('#315567'),lime=mat(color),dark=mat('#29353b');const box=(x,y,z,m,px=0,py=0,pz=0,parent=scene)=>{const o=new T.Mesh(new T.BoxGeometry(x,y,z),m);o.position.set(px,py,pz);o.receiveShadow=true;parent.add(o);return o};box(120000,1,120000,grass,0,-1,-20000);
const markings=[];function airport(z,code){box(60,.08,3400,asphalt,0,.02,z-1700);box(18,.06,3650,concrete,160,.03,z-1800);box(500,.06,750,concrete,400,.03,z-1600);box(420,28,90,dark,550,14,z-1450);box(415,14,2,glass,550,18,z-1404);box(26,65,26,concrete,300,32,z-950);box(54,14,45,glass,300,66,z-950);for(let i=0;i<6;i++){box(60,8,20,concrete,400+i*50,6,z-1340);box(14,4,95,dark,400+i*50,4,z-1330);}
for(let i=0;i<30;i++)markings.push(box(1.4,.15,32,white,0,.12,z-100-i*108));for(const side of [-1,1]){box(.7,.14,3400,white,side*29,.1,z-1700);for(let i=0;i<8;i++){box(2,.15,40,white,side*(5+i*2.6),.12,z-32)}for(let i=0;i<42;i++){const bulb=new T.Mesh(new T.SphereGeometry(.65,6,4),new T.MeshBasicMaterial({color:'#c7efff'}));bulb.position.set(side*31,.55,z-i*82);scene.add(bulb)}box(8,.15,52,white,side*14,.12,z-310);box(8,.15,52,white,side*14,.12,z-460);}
for(let i=0;i<8;i++){const approach=new T.Mesh(new T.SphereGeometry(.8,6,4),new T.MeshBasicMaterial({color:'#fff3c2'}));approach.position.set(0,.55,z+60+i*60);scene.add(approach)}
const cv=document.createElement('canvas');cv.width=512;cv.height=128;const ctx=cv.getContext('2d');ctx.fillStyle='#e3e9e5';ctx.font='bold 84px sans-serif';ctx.textAlign='center';ctx.fillText('36',256,98);const tex=new T.CanvasTexture(cv);const plane=new T.Mesh(new T.PlaneGeometry(15,6),new T.MeshBasicMaterial({map:tex,transparent:true}));plane.rotation.x=-Math.PI/2;plane.position.set(0,.15,z-85);scene.add(plane);const sign=box(55,10,1,dark,80,7,z-180);const label=document.createElement('canvas');label.width=512;label.height=128;const lc=label.getContext('2d');lc.fillStyle='#c6ed89';lc.font='bold 56px sans-serif';lc.fillText(code+' / ALPHA',10,80);const lt=new T.CanvasTexture(label);sign.material=new T.MeshBasicMaterial({map:lt});}
airport(0,'DEP');airport(DESTINATION,'ARR');
// Deterministic terrain, ocean and city blocks, all original procedural scenery.
box(22000,.1,120000,new T.MeshStandardMaterial({color:night?'#12293e':'#4e91ab',roughness:.3}),-22000,-.25,-20000);
let seed=123;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};const buildings=new T.InstancedMesh(new T.BoxGeometry(1,1,1),mat('#a9b3b0'),180),dummy=new T.Object3D();for(let i=0;i<180;i++){const h=12+rand()*65;dummy.position.set(1400+rand()*4500,h/2,-500-rand()*23500);dummy.scale.set(30+rand()*70,h,30+rand()*70);dummy.updateMatrix();buildings.setMatrixAt(i,dummy.matrix)}scene.add(buildings);for(let i=0;i<18;i++){const h=200+rand()*700,o=new T.Mesh(new T.ConeGeometry(800+rand()*700,h,8),mat('#6c857a'));o.position.set(6500+rand()*5000,h/2,-rand()*30000);scene.add(o)}
const clouds=new T.Group();scene.add(clouds);const cloudMaterial=new T.MeshLambertMaterial({color:night?'#708094':'#f5f5ee',transparent:true,opacity:s.weather==='storm'?.7:.87});for(let i=0;i<24;i++){const c=new T.Group();for(let j=0;j<3;j++){const m=new T.Mesh(new T.SphereGeometry(100+rand()*100,8,6),cloudMaterial);m.scale.set(2,.65,1);m.position.set(j*170,rand()*30,0);c.add(m)}c.position.set((rand()-.5)*16000,1100+rand()*1100,-rand()*28000);clouds.add(c)}
const aircraft=new T.Group(),detail=new T.Group(),proxy=new T.Group();aircraft.add(detail,proxy);scene.add(aircraft);const a=airframe(s.model);function fallback(){const fus=new T.Mesh(new T.CylinderGeometry(1.75,1.75,a.length*.76,16),mat('#ecece7'));fus.rotation.x=Math.PI/2;detail.add(fus);const nose=new T.Mesh(new T.ConeGeometry(1.75,a.length*.14,16),white);nose.rotation.x=-Math.PI/2;nose.position.z=-a.length*.45;detail.add(nose);const wingGeo=new T.BufferGeometry();const v=[0,0,-3,a.span/2,.2,6,a.span/2,.2,8,0,0,4,0,0,-3,0,0,4,-a.span/2,.2,8,-a.span/2,.2,6];wingGeo.setAttribute('position',new T.Float32BufferAttribute(v,3));wingGeo.setIndex([0,1,2,0,2,3,4,5,6,4,6,7]);wingGeo.computeVertexNormals();const wing=new T.Mesh(wingGeo,new T.MeshStandardMaterial({color:'#ced6d9',side:T.DoubleSide}));detail.add(wing);box(1,5,8,lime,0,2,a.length*.34,detail);box(14,.25,3,white,0,1,a.length*.34,detail);for(const side of [-1,1]){const eng=new T.Mesh(new T.CylinderGeometry(1.2,1.1,4,16),dark);eng.rotation.x=Math.PI/2;eng.position.set(side*a.span*.18,-1.2,0);detail.add(eng)}detail.position.y=1;}
fallback();box(3,2,a.length*.8,white,0,1,0,proxy);box(a.span,.15,5,concrete,0,1,1,proxy);const gearGroup=new T.Group();aircraft.add(gearGroup);for(const x of [-2,2,0]){const z=x===0?-a.length*.3:2;box(.16,1.7,.16,dark,x,-.7,z,gearGroup);const wheel=new T.Mesh(new T.CylinderGeometry(.65,.65,x===0?.65:1.2,10),dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x,-1.5,z);gearGroup.add(wheel)}
// Original interactive flight-deck shell; licensed external mesh is exterior-only.
const cockpit=new T.Group();aircraft.add(cockpit);const cockpitZ=-a.length*.39;box(6,.25,4,dark,0,-.2,cockpitZ,cockpit);box(5.6,1.05,.25,dark,0,.3,cockpitZ-1.3,cockpit);const screens=new T.Mesh(new T.PlaneGeometry(3.8,.75),new T.MeshBasicMaterial({color:'#132934'}));screens.position.set(0,.42,cockpitZ-1.15);cockpit.add(screens);for(const side of [-1,1]){box(.16,3,.16,dark,side*1.9,1.3,cockpitZ-2.2,cockpit);const pillar=box(.16,3,.16,dark,side*.8,1.4,cockpitZ-2.6,cockpit);pillar.rotation.z=side*.2;}const controls3d=[];for(const [name,x] of [['gear',1.6],['flaps',1],['brake',-.9]]){const c=box(.28,.18,.35,lime,x,.85,cockpitZ-1.05,cockpit);c.userData.control=name;controls3d.push(c)}
let modelLoaded=false;const textureOriginals=new Map();function textureQuality(limit){detail.traverse(o=>{if(!o.isMesh)return;(Array.isArray(o.material)?o.material:[o.material]).filter(Boolean).forEach(m=>{for(const texture of Object.values(m)){if(!texture?.isTexture||!texture.image)continue;if(!textureOriginals.has(texture))textureOriginals.set(texture,texture.image);const original=textureOriginals.get(texture);const w=original.width||1,h=original.height||1;if(Math.max(w,h)>limit){const c=document.createElement('canvas');const ratio=limit/Math.max(w,h);c.width=Math.max(1,Math.round(w*ratio));c.height=Math.max(1,Math.round(h*ratio));c.getContext('2d').drawImage(original,0,0,c.width,c.height);texture.image=c;texture.needsUpdate=true}else if(texture.image!==original){texture.image=original;texture.needsUpdate=true}}})})}const asset=ASSETS[s.model];const assetPromise=(async()=>{if(renderer.software){onAsset('軟體 3D 備援 · 程序化外觀 / 無貼圖 · 相同飛行物理');return}if(!asset){onAsset('程序化替代外觀（尚無專屬 GLB）');return}try{const gltf=await new GLTFLoader().loadAsync('/assets/flight/'+asset.file+'.glb');if(disposed){disposeObject(gltf.scene);return}const imported=new T.Group();imported.add(gltf.scene);imported.rotation.set(...asset.rotation);imported.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(imported),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3());const factor=asset.length/Math.max(size.x,size.z);imported.scale.setScalar(factor);imported.position.set(-center.x*factor,-.6-bounds.min.y*factor,-center.z*factor);imported.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{m.side=T.DoubleSide;m.roughness=.65})}}});disposeObject(detail);detail.clear();detail.position.y=0;detail.add(imported);textureQuality(QUALITY[tier].texture);modelLoaded=true;onAsset(asset.label)}catch(e){onAsset('GLB 載入失敗，使用明確標示的程序化外觀')}})();
let lastMode='chase',tier=quality;function setQuality(level){tier=level;const p=QUALITY[level];renderer.setPixelRatio(Math.min(devicePixelRatio||1,p.dpr)*p.scale);textureQuality(p.texture);renderer.shadowMap.enabled=p.shadow;renderer.shadowMap.type=T.PCFSoftShadowMap;camera.far=p.distance;camera.updateProjectionMatrix();scene.fog.far=p.distance;clouds.children.forEach((c,i)=>c.visible=i<p.clouds);detail.traverse(o=>{if(o.isMesh){const ms=Array.isArray(o.material)?o.material:[o.material];ms.filter(Boolean).forEach(m=>{if(m.map)m.map.anisotropy=level==='high'?4:1})}})}setQuality(quality);
function resize(w,h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
const raycaster=new T.Raycaster();function pick(x,y){raycaster.setFromCamera(new T.Vector2(x,y),camera);return raycaster.intersectObjects(controls3d)[0]?.object.userData.control}
function draw(mode='chase',dt=1/60){aircraft.position.fromArray(s.pos);aircraft.quaternion.fromArray(s.q);gearGroup.visible=s.gear;cockpit.visible=mode==='cockpit';detail.visible=mode!=='cockpit';proxy.visible=false;if(mode!=='cockpit'&&camera.position.distanceTo(aircraft.position)>900){detail.visible=false;proxy.visible=true}const pos=new T.Vector3().fromArray(s.pos),q=new T.Quaternion().fromArray(s.q);let offset,target;if(mode==='cockpit'){offset=new T.Vector3(0,2.1,cockpitZ-.1).applyQuaternion(q);target=new T.Vector3(0,1.4,-a.length-140).applyQuaternion(q)}else if(mode==='wing'){offset=new T.Vector3(a.span*.48,6,3).applyQuaternion(q);target=new T.Vector3(0,0,-120).applyQuaternion(q)}else if(mode==='tower'){offset=new T.Vector3(100,80,150);target=new T.Vector3(0,0,-50)}else{offset=new T.Vector3(0,a.length*.37,a.length*1.55).applyQuaternion(q);target=new T.Vector3(0,a.length*.06,-a.length*.4).applyQuaternion(q)}const desired=pos.clone().add(offset);if(lastMode!==mode||mode==='cockpit'||mode==='wing')camera.position.copy(desired);else camera.position.lerp(desired,Math.min(1,dt*5));camera.up.copy(mode==='cockpit'||mode==='wing'?new T.Vector3(0,1,0).applyQuaternion(q):new T.Vector3(0,1,0));camera.lookAt(pos.add(target));lastMode=mode;sun.position.set(s.pos[0]-800,s.pos[1]+1500,s.pos[2]+500);sun.target.position.fromArray(s.pos);renderer.render(scene,camera)}
return {renderer,resize,draw,setQuality,pick,assetPromise,dispose(){disposed=true;textureOriginals.forEach(i=>i.close?.());disposeObject(scene);renderer.dispose();renderer.forceContextLoss()}}}
function disposeObject(root){const geometries=new Set(),materials=new Set(),textures=new Set();root.traverse(o=>{if(o.geometry)geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).filter(Boolean).forEach(m=>materials.add(m))});materials.forEach(m=>Object.values(m).forEach(v=>{if(v?.isTexture)textures.add(v)}));textures.forEach(t=>{t.source?.data?.close?.();t.dispose()});materials.forEach(m=>m.dispose());geometries.forEach(g=>g.dispose())}
