import {airports,aircraft,airport,model,goals,events,research} from './data.js';
export const VERSION=1;export const DAY_MS=30000;
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
export function distance(from,to){const a=airport(from),b=airport(to),r=Math.PI/180;const h=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lon-a.lon)*r/2)**2;return Math.round(12742*Math.asin(Math.sqrt(clamp(h,0,1))))}
export function fresh(name='SKYLINE AIR',hub='TPE'){return {version:VERSION,name:name.trim().slice(0,28)||'SKYLINE AIR',hub,cash:8500000,debt:0,day:1,xp:0,rep:70,pax:0,flights:0,fleet:[{id:1,model:'e195',condition:100}],routes:[],research:{fuel:0,service:0,marketing:0,maintenance:0},claimed:[],history:[],log:[],nextId:2,seed:7331,event:null,effect:null,lastTick:Date.now(),active:true,cycle:1,contract:{startPax:0,target:6000,reward:400000,deadline:16}}}
export function level(s){return Math.min(50,1+Math.floor(Math.sqrt(s.xp/120)))}
export function rng(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
export function forecast(s,r){const plane=s.fleet.find(p=>p.id===r.plane);if(!plane)return null;const m=model(plane.model),km=distance(r.from,r.to);const hours=km/m.speed*2+1.4;const rotations=Math.max(1,Math.floor(22/hours));const baseFare=Math.round(45+km*.075);const demand=(260+km*.025)*airport(r.to).demand*(.65+s.rep/150)*(1+s.research.marketing*.08+s.research.service*.035)*(s.effect?.type==='demand'?s.effect.value:1)*(1+.08*Math.sin(s.day/12));const ratio=clamp(r.fare/baseFare,.35,3.5);const dailyDemand=demand/ratio**1.6;const capacity=m.seats*2*rotations;const load=clamp(dailyDemand/capacity,.08,.98);const pax=Math.floor(capacity*load);const revenue=pax*r.fare;const fuel=km*2*rotations*m.burn*.72*(1-s.research.fuel*.06)*(s.effect?.type==='fuel'?s.effect.value:1);const cost=Math.round(fuel+rotations*(m.seats*23+4500)+m.price*.0008);return {km,rotations,baseFare,load,pax,revenue,cost,profit:Math.round(revenue-cost),hours}}
const note=(s,message)=>{s.log.unshift({day:s.day,message});s.log=s.log.slice(0,35)};
function spend(s,cost){if(s.cash<cost)throw Error('資金不足，先營運航線或申請貸款。');s.cash-=cost}
function applyCommand(s,type,p={}){switch(type){
case 'buy':{const m=model(p.model);if(!m)throw Error('無效機型');if(level(s)<m.level)throw Error('航空公司等級不足');if(s.fleet.length>=60)throw Error('機隊已達 60 架上限');spend(s,m.price);s.fleet.push({id:s.nextId++,model:m.id,condition:100});note(s,`交付 ${m.name}`);break}
case 'route':{const plane=s.fleet.find(f=>f.id===Number(p.plane));if(!plane)throw Error('請選擇飛機');if(s.routes.some(r=>r.plane===plane.id))throw Error('這架飛機已有航班安排');if(!airport(p.to)||p.to===s.hub)throw Error('請選擇其他目的地');if(s.routes.some(r=>r.to===p.to&&r.from===s.hub))throw Error('這條航線已經開通');const km=distance(s.hub,p.to);if(km>model(plane.model).range)throw Error('距離超出飛機航程');spend(s,80000+km*15);const fare=Number(p.fare);if(!Number.isFinite(fare)||fare<20||fare>2500)throw Error('票價需介於 $20 與 $2,500');s.routes.push({id:s.nextId++,plane:plane.id,from:s.hub,to:p.to,fare,active:true});note(s,`開通 ${s.hub} → ${p.to}`);break}
case 'fare':{const r=s.routes.find(r=>r.id===Number(p.id));const fare=Number(p.fare);if(!r||!Number.isFinite(fare)||fare<20||fare>2500)throw Error('票價需介於 $20 與 $2,500');r.fare=fare;break}
case 'pause':{const r=s.routes.find(r=>r.id===Number(p.id));if(r)r.active=!r.active;break}
case 'close':s.routes=s.routes.filter(r=>r.id!==Number(p.id));break;
case 'maintain':{const f=s.fleet.find(f=>f.id===Number(p.id));if(!f)throw Error('飛機不存在');spend(s,Math.ceil((100-f.condition)*model(f.model).price*.00015));f.condition=100;note(s,`B-${String(f.id).padStart(4,'0')} 維護完成`);break}
case 'sell':{const f=s.fleet.find(f=>f.id===Number(p.id));if(!f)throw Error('飛機不存在');if(s.routes.some(r=>r.plane===f.id))throw Error('先關閉這架飛機的航線');s.cash+=Math.round(model(f.model).price*.65*(.6+f.condition*.004));s.fleet=s.fleet.filter(x=>x.id!==f.id);break}
case 'research':{const r=research.find(r=>r.id===p.id);if(!r||s.research[r.id]>=r.max)throw Error('此研究已完成');spend(s,r.base*(s.research[r.id]+1)**2);s.research[r.id]++;s.xp+=45;note(s,`${r.name}提升至 ${s.research[r.id]} 級`);break}
case 'loan':if(s.debt>=10000000)throw Error('貸款已達上限');s.cash+=2000000;s.debt+=2000000;note(s,'取得 $2,000,000 貸款，每日利息 0.08%');break;
case 'repay':{const amount=Math.min(2000000,s.debt);spend(s,amount);s.debt-=amount;break}
case 'claim':{const g=goals.find(g=>g.id===p.id);if(!g||s.claimed.includes(g.id)||progress(s,g)<g.target)throw Error('目標尚未達成');s.cash+=g.reward;s.xp+=100;s.claimed.push(g.id);note(s,`達成：${g.name}`);break}
case 'event':if(s.event){if(p.accept&&s.event.type==='choice'){spend(s,s.event.cost);s.cash+=s.event.reward;s.rep=clamp(s.rep+(s.event.rep||1),0,100)}s.event=null}break;
case 'contract':{const c=s.contract;if(!c||s.pax-c.startPax<c.target)throw Error('委託尚未完成');s.cash+=c.reward;s.rep=clamp(s.rep+1,0,100);s.xp+=80;s.cycle++;s.contract={startPax:s.pax,target:Math.min(180000,6000+s.cycle*2500),reward:Math.min(3000000,400000+s.cycle*120000),deadline:s.day+15};note(s,'完成董事會委託，下一份合約已送達');break}
case 'hub':if(!airport(p.hub))throw Error('機場不存在');if(s.routes.length)throw Error('先關閉航線才能遷移基地');spend(s,1000000);s.hub=p.hub;break;
default:throw Error('未知操作')
}return s}
export function act(s,type,p={}){const next=structuredClone(s);applyCommand(next,type,p);Object.assign(s,next);return s}
export function progress(s,g){if(g.metric==='routes')return s.routes.length;if(g.metric==='fleet')return s.fleet.length;if(g.metric==='regions')return new Set([airport(s.hub).region,...s.routes.map(r=>airport(r.to).region)]).size;return s[g.metric]}
export function tick(s){s.day++;if(s.contract&&s.day>s.contract.deadline){note(s,'董事會委託到期，已更新新目標');s.contract={...s.contract,startPax:s.pax,deadline:s.day+15}}let revenue=0,cost=1200+s.fleet.length*1800+Math.round(s.debt*.0008),pax=0,flights=0;const previousLevel=level(s);for(const r of s.routes){if(!r.active)continue;const f=s.fleet.find(f=>f.id===r.plane);if(!f||f.condition<20)continue;const estimate=forecast(s,r);const weather=rng(s)<.06;const multiplier=weather?.55:.9+rng(s)*.2;const passengers=Math.round(estimate.pax*multiplier);revenue+=passengers*r.fare;cost+=estimate.cost;pax+=passengers;flights+=estimate.rotations*2;f.condition=clamp(f.condition-estimate.rotations*.13*(1-s.research.maintenance*.12),0,100);if(f.condition<20)note(s,`${model(f.model).name} 停飛，請進行維護`);if(weather)s.rep=clamp(s.rep-.08,0,100)}s.cash+=revenue-cost;s.pax+=pax;s.flights+=flights;s.xp+=flights*.5+pax*.006;s.rep=clamp(s.rep+(pax>0?.012:0),0,100);s.history.push({day:s.day,revenue,cost,profit:revenue-cost,pax});s.history=s.history.slice(-60);if(level(s)>previousLevel)note(s,`航空公司升至 Level ${level(s)}`);if(s.effect&&s.day>s.effect.until)s.effect=null;if(s.day%7===0&&!s.event){const e={...events[Math.floor(rng(s)*events.length)]};s.event=e;if(e.type!=='choice')s.effect={type:e.type,value:e.value,until:s.day+4};note(s,e.title)}if(s.cash<-2000000){s.active=false;note(s,'資金低於負 $2,000,000，營運暫停。可貸款或出售閒置飛機。')}return s}
export function validate(raw){if(!raw||raw.version!==VERSION)throw Error('不支援的存檔版本');const s=structuredClone(raw);for(const key of ['cash','debt','day','xp','rep','pax','flights','nextId','seed','cycle'])if(!Number.isFinite(s[key]))throw Error('存檔數值損毀');if(s.day<1||s.day>10000000||s.debt<0||s.debt>10000000||s.rep<0||s.rep>100||s.xp<0||s.pax<0||s.flights<0)throw Error('存檔數值超出範圍');if(!airport(s.hub)||typeof s.name!=='string')throw Error('無效航空公司');s.name=s.name.slice(0,28);if(!Array.isArray(s.fleet)||s.fleet.length>60||!Array.isArray(s.routes)||s.routes.length>60)throw Error('機隊資料損毀');const ids=new Set();for(const f of s.fleet){if(!model(f.model)||!Number.isInteger(f.id)||ids.has(f.id)||!Number.isFinite(f.condition)||f.condition<0||f.condition>100)throw Error('無效機隊');ids.add(f.id)}const used=new Set(),routeIds=new Set();for(const r of s.routes){if(!Number.isInteger(r.id)||ids.has(r.id)||routeIds.has(r.id)||!ids.has(r.plane)||used.has(r.plane)||!airport(r.from)||!airport(r.to)||r.from!==s.hub||r.from===r.to||!Number.isFinite(r.fare)||r.fare<20||r.fare>2500||distance(r.from,r.to)>model(s.fleet.find(f=>f.id===r.plane).model).range)throw Error('無效航線');used.add(r.plane);routeIds.add(r.id);r.active=!!r.active}for(const r of research)if(!Number.isInteger(s.research?.[r.id])||s.research[r.id]<0||s.research[r.id]>r.max)throw Error('無效研究');if(!Array.isArray(s.claimed)||!Array.isArray(s.history)||!Array.isArray(s.log))throw Error('存檔資料損毀');s.claimed=s.claimed.filter(id=>goals.some(g=>g.id===id));s.history=s.history.filter(h=>['day','profit','revenue','cost','pax'].every(k=>Number.isFinite(h[k]))).slice(-60);s.log=s.log.filter(l=>typeof l.message==='string'&&Number.isFinite(l.day)).slice(0,35);s.event=events.find(e=>e.title===s.event?.title)?{...events.find(e=>e.title===s.event.title)}:null;s.effect=['demand','fuel'].includes(s.effect?.type)&&Number.isFinite(s.effect.until)&&Number.isFinite(s.effect.value)?{type:s.effect.type,until:s.effect.until,value:clamp(s.effect.value,.5,1.5)}:null;if(!s.contract||!['startPax','target','reward','deadline'].every(k=>Number.isFinite(s.contract[k]))||s.contract.startPax<0||s.contract.target<1||s.contract.target>180000||s.contract.reward<0||s.contract.reward>3000000)s.contract={startPax:s.pax,target:6000,reward:400000,deadline:s.day+15};s.active=!!s.active;s.lastTick=Number.isFinite(s.lastTick)?s.lastTick:Date.now();s.nextId=Math.max(s.nextId,...s.fleet.map(f=>f.id+1),...s.routes.map(r=>r.id+1));return s}
export function catchUp(s,now=Date.now()){const days=Math.min(180,Math.max(0,Math.floor((now-s.lastTick)/DAY_MS)));if(s.active)for(let i=0;i<days&&s.active;i++)tick(s);s.lastTick=now;return days}
