import {airports,aircraft,airport,model} from './data.js';
import {level,forecast,staffStatus,distance} from './engine.js';
import {facilities,cabins,catering,hubSlots,usedMarket,leaseDaily,marketClimate,achievements} from './expansion.js';
const money=n=>'$'+Math.round(n).toLocaleString('en-US'),num=n=>Math.round(n).toLocaleString(),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,text,attrs='',disabled=false)=>`<button class="small ghost" data-action="${action}" ${attrs} ${disabled?'disabled':''}>${text}</button>`;
const hero=(eyebrow,title,text)=>`<div class="expansion-hero"><div><span class="eyebrow">${eyebrow}</span><h2>${title}</h2><p>${text}</p></div><span class="hero-orbit">✈</span></div>`;
export function empire(s){return hero('NETWORK DEVELOPMENT','從單一基地，到全球航空集團','建立最多 6 座基地，從各基地開通航線。建設航廈、貴賓室、機棚與貨運中心。')+`<section class="panel"><div class="panel-body hub-form"><select id="new-hub" aria-label="新基地">${airports.filter(a=>!s.hubs.includes(a.code)).map(a=>`<option value="${a.code}">${a.code} · ${a.name}</option>`).join('')}</select>${button('open-hub-confirm',level(s)<3?'Lv.3 解鎖第二基地':'建立基地 · $1,500,000','',s.hubs.length>=6||level(s)<3)}</div></section><div class="hub-grid">${s.hubs.map(code=>`<section class="panel"><div class="panel-head"><div><span class="eyebrow">${code===s.hub?'HEADQUARTERS':'REGIONAL HUB'}</span><h2>${code} · ${airport(code).name}</h2></div><span class="badge">${s.routes.filter(r=>r.from===code).length} / ${hubSlots(s,code)} 航線</span></div><div class="panel-body">${facilities.map(f=>{const lv=s.facilities[code][f.id];return `<div class="facility"><div><strong>${f.icon} ${f.name}</strong><p>${f.text} · Lv.${lv}/3</p></div>${button('facility',lv>=3?'已完成':money(f.cost*(lv+1)**2),`data-hub="${code}" data-id="${f.id}"`,lv>=3||s.cash<f.cost*(lv+1)**2)}</div>`}).join('')}${button('hub-route','＋ 從此基地規劃航線',`data-hub="${code}"`)}</div></section>`).join('')}</div>`}
export function strategy(s){const candidates=airports.filter(a=>a.code!==s.hub).map(a=>{const climate=marketClimate(s,a.code);return {a,score:a.demand*climate.demand*climate.competition,climate}}).sort((a,b)=>b.score-a.score).slice(0,8);return hero('COMMERCIAL STRATEGY','每一個決策，都有代價','抓住旺季市場、建立常客會員、增加附加收入，管理燃油與機隊風險。')+`<div class="stats"><div class="stat"><label>燃油價格指數</label><strong>${s.fuelPrice.toFixed(2)}×</strong><small>${s.hedge?'避險固定 '+s.hedge.price.toFixed(2)+'×':'每日隨市場波動'}</small></div><div class="stat"><label>常客會員</label><strong>Lv.${s.loyalty}</strong><small>每級需求 +2.5%</small></div><div class="stat"><label>累積貨運</label><strong>${num(s.totalCargo)} t</strong><small>${s.cargo?'腹艙貨運已啟用':'可投入腹艙或專機貨運'}</small></div><div class="stat"><label>附加服務</label><strong>Lv.${s.ancillary}</strong><small>每級每位旅客增加 $3 收入</small></div></div><div class="grid">${[
['loyalty','常客會員計畫','提高回流旅客需求，每級 +2.5%。',s.loyalty>=5?'已滿級':money(250000*(s.loyalty+1)**2),s.loyalty>=5],
['ancillary','選位與附加服務','建立選位、加購行李與服務收益。',s.ancillary>=5?'已滿級':money(180000*(s.ancillary+1)**2),s.ancillary>=5],
['cargo-enable','腹艙貨運','利用客機腹艙運送貨物，額外收入與運量納入報表。',s.cargo?'已啟用':'啟用 · $80,000',!!s.cargo],
['campaign','全球宣傳活動','7 天旅客需求 +15%，可與會員及貴賓室效果疊加。',s.campaign?'活動至 Day '+s.campaign.until:'啟動 · $75,000',!!s.campaign],
['hedge','燃油價格避險','支付固定費用，鎖定目前價格 20 天。油價下跌時也無法改價。',s.hedge?'合約至 Day '+s.hedge.until:'鎖定 · $200,000',!!s.hedge],
['auto-maintain','自動維護調度','機況低於 35% 時，資金足夠會自动支付維護費，避免停飛。',s.autoMaintain?'已啟用 · 點擊關閉':'啟用自動維護',false],
['insurance','航班延誤保障','每天每架 $950。遇到天候時保留 80% 收益，而非 55%。',s.insurance?'已啟用 · 點擊關閉':'啟用保障',false]
].map(([action,title,text,label,disabled])=>`<article class="air-card"><span class="eyebrow">AIRLINE MANAGEMENT</span><h2>${title}</h2><p>${text}</p><footer>${button(action,label,'',disabled)}</footer></article>`).join('')}</div><section class="panel" style="margin-top:24px"><div class="panel-head"><h2>市場雷達 · 熱門目的地</h2><span class="badge">DAY ${s.day}</span></div><div class="table-wrap"><table><thead><tr><th>目的地</th><th>季節</th><th>需求指數</th><th>競爭壓力</th><th>距離 / 主基地</th></tr></thead><tbody>${candidates.map(({a,climate,score})=>`<tr><td><strong>${a.code}</strong> · ${a.name}</td><td>${climate.season}</td><td>${score.toFixed(2)}×</td><td>${climate.competition<.94?'較強':'一般'}</td><td>${num(distance(s.hub,a.code))} km</td></tr>`).join('')}</tbody></table></div></section>`}
export function missionsPage(s){const c=s.challenge,value=c?Math.max(0,(c.metric==='cargo'?s.totalCargo:s[c.metric])-c.start):0;return hero('THE NEXT CHAPTER','新的委託，新的野心','企業每 7 天發布新委託。完成永久成就，建立航空集團的長期目標。')+`<section class="panel"><div class="panel-head"><h2>企業招標中心</h2><span class="badge">${c?'#'+c.cycle:'等待下一輪'}</span></div><div class="panel-body">${c?`<h2>${{pax:'旅客運輸',flights:'航班營運',cargo:'貨物運送'}[c.metric]}：${num(c.target)} ${c.metric==='cargo'?'噸':c.metric==='flights'?'架次':'人'}</h2><p class="note">Day ${c.until} 前完成 · 獎勵 ${money(c.reward)} · 目前 ${num(value)} / ${num(c.target)}</p><div class="progress"><i style="width:${Math.min(100,value/c.target*100)}%"></i></div>${button('challenge-claim','領取委託獎勵','',value<c.target)}`:'<p class="note">下一個 Day '+(Math.floor(s.day/7)+1)*7+' 開放招標。董事會委託可在營運中心持續接取。</p>'}</div></section><div class="grid" style="margin-top:24px">${achievements.map(a=>{const v=a.value(s),claimed=s.achievements.includes(a.id);return `<article class="air-card"><span class="eyebrow">${claimed?'COMPLETED':'CAREER ACHIEVEMENT'}</span><h2>${a.name}</h2><p>${num(Math.min(a.target,v))} / ${num(a.target)}</p><div class="progress"><i style="width:${Math.min(100,v/a.target*100)}%"></i></div><footer><strong>${money(a.reward)}</strong>${button('achievement',claimed?'已領取':'領取',`data-id="${a.id}"`,claimed||v<a.target)}</footer></article>`}).join('')}</div><section class="panel" style="margin-top:24px"><div class="panel-head"><h2>航空市場快訊</h2></div>${s.news.map(n=>`<div class="log"><span>DAY ${n.day}</span>${esc(n.text)}</div>`).join('')||'<div class="panel-body note">市場動態與新委託將顯示在這裡。</div>'}</section>`}
export function usedPage(s,photo){return hero('PRE-OWNED AIRCRAFT','中古機交易所','每 7 天更新。低價格、較低機況；接手後要評估維護費與人員成本。')+`<div class="grid">${usedMarket(s).map(d=>{const m=model(d.model);return `<article class="air-card">${photo(m)}<h2>${m.name}</h2><p>機況 ${d.condition}% · 使用歷史 200 天 · 原價 ${money(m.price)}</p><div class="specs"><div><strong>${m.seats||m.cargo}</strong><small>${m.cargo?'載重 t':'座位'}</small></div><div><strong>${num(m.range)}</strong><small>航程 km</small></div><div><strong>${Math.round(100-d.price/m.price*100)}%</strong><small>折扣</small></div></div><footer><strong>${money(d.price)}</strong>${button('used-confirm',d.sold?'已售出':level(s)<m.level?'Lv.'+m.level:'查看交易',`data-id="${d.id}"`,d.sold||level(s)<m.level)}</footer></article>`}).join('')}</div>`}
export function cabinDialog(s,id){const f=s.fleet.find(f=>f.id===Number(id)),m=model(f.model);return `<p>${m.name} · 現有 ${cabins.find(c=>c.id===f.cabin)?.name||'標準客艙'}。改裝費立即支付，舊改裝費不退回。</p><div class="incident-options">${cabins.map(c=>`<button class="ghost incident-option" data-action="cabin" data-id="${f.id}" data-cabin="${c.id}" ${f.cabin===c.id?'disabled':''}><strong>${c.name} · ${Math.floor(m.seats*c.capacity)} 席</strong><small>平均票價 ×${c.fare} · 需求 ×${c.demand} · 改裝 ${money(m.price*(c.cost||.01))}</small></button>`).join('')}</div>`}
export function flightDesk(s){const estimates=s.routes.filter(r=>r.active).map(r=>({r,e:forecast(s,r)})),crew=staffStatus(s);return `<section class="flight-desk"><div><span class="eyebrow">OPERATIONS DESK</span><h2>今日航班調度</h2><p>${s.hubs.length} 座基地 · ${num(estimates.reduce((n,x)=>n+x.e.rotations*2,0))} 計畫架次 · 人員 ${Math.round(crew.coverage*100)}%</p></div><div><strong>${money(estimates.reduce((n,x)=>n+x.e.profit,0)-crew.payroll-s.fleet.reduce((n,f)=>n+leaseDaily(f),0))}</strong><small>航線收益減薪資與租金預估；尚未扣其他固定成本</small></div></section>`}
