import {airports,airport,model} from './data.js';
export const facilities=[{id:'terminal',name:'航廈與登機門',icon:'▦',text:'每級增加 8 條基地航線容量',cost:650000},{id:'lounge',name:'貴賓室',icon:'◇',text:'每級提高基地旅客需求 4%',cost:450000},{id:'hangar',name:'維修機棚',icon:'⚙',text:'每級降低機況磨損 12%',cost:550000},{id:'cargo',name:'貨運中心',icon:'▤',text:'每級提高基地貨運需求 10%',cost:500000}];
export const cabins=[{id:'standard',name:'標準客艙',capacity:1,fare:1,demand:1,cost:0},{id:'dense',name:'高密度經濟艙',capacity:1.16,fare:.9,demand:1.06,cost:.015},{id:'business',name:'商務混合艙',capacity:.82,fare:1.3,demand:1.04,cost:.035},{id:'first',name:'旗艦客艙',capacity:.65,fare:1.65,demand:.94,cost:.055}];
export const catering=[{id:'basic',name:'基本服務',demand:1,cost:0},{id:'standard',name:'熱食與娛樂',demand:1.05,cost:8},{id:'premium',name:'精品餐飲',demand:1.12,cost:22}];
export function defaults(hub){return {edition:2,hubs:[hub],hubLimits:{[hub]:10},facilities:{[hub]:{terminal:0,lounge:0,hangar:0,cargo:0}},loyalty:0,cargo:0,totalCargo:0,ancillary:0,autoMaintain:false,insurance:false,campaign:null,hedge:null,fuelPrice:1,challenge:null,challengeCycle:0,usedBought:[],news:[],achievements:[],totalRevenue:0,totalCost:0}}
const bounded=(v,a,b,f=0)=>Number.isFinite(v)?Math.min(b,Math.max(a,v)):f;
export function migrateExpansion(s){const hadLimits=s.hubLimits!==undefined;const d=defaults(s.hub);for(const [k,v] of Object.entries(d))if(s[k]===undefined)s[k]=structuredClone(v);s.edition=2;
if(!Array.isArray(s.hubs)||s.hubs.length>6||s.hubs.some(c=>!airport(c))||!s.hubs.includes(s.hub)||new Set(s.hubs).size!==s.hubs.length)throw Error('基地資料損毀');
s.hubLimits=s.hubLimits||{};if(!hadLimits)s.hubLimits=Object.fromEntries(s.hubs.map(h=>[h,Math.max(10,s.routes.filter(r=>r.from===h).length)]));for(const h of s.hubs)s.hubLimits[h]=Math.floor(bounded(s.hubLimits[h],10,60,Math.max(10,s.routes.filter(r=>r.from===h).length)));s.facilities=s.facilities&&typeof s.facilities==='object'?s.facilities:{};for(const hub of s.hubs){const fs=s.facilities[hub]||{};for(const f of facilities)if(fs[f.id]!==undefined&&(!Number.isInteger(fs[f.id])||fs[f.id]<0||fs[f.id]>3))throw Error('機場設施資料損毀');s.facilities[hub]=Object.fromEntries(facilities.map(f=>[f.id,fs[f.id]||0]))}
for(const k of ['loyalty','ancillary'])s[k]=Math.floor(bounded(s[k],0,5));for(const k of ['cargo','totalCargo','totalRevenue','totalCost'])s[k]=bounded(s[k],0,1e15);s.fuelPrice=bounded(s.fuelPrice,.65,1.6,1);s.autoMaintain=!!s.autoMaintain;s.insurance=!!s.insurance;
s.campaign=s.campaign&&Number.isFinite(s.campaign.until)?{until:s.campaign.until}:null;s.hedge=s.hedge&&Number.isFinite(s.hedge.until)&&Number.isFinite(s.hedge.price)?{until:s.hedge.until,price:bounded(s.hedge.price,.65,1.6,1)}:null;
s.usedBought=Array.isArray(s.usedBought)?s.usedBought.filter(x=>typeof x==='string').slice(-100):[];s.news=Array.isArray(s.news)?s.news.filter(x=>typeof x.text==='string'&&Number.isFinite(x.day)).slice(0,12):[];s.achievements=Array.isArray(s.achievements)?s.achievements.filter(x=>achievements.some(a=>a.id===x)):[];s.challengeCycle=Math.floor(bounded(s.challengeCycle,0,1e8));if(s.challenge){const c=s.challenge;if(!['pax','flights','cargo'].includes(c.metric)||!['target','start','reward','until','cycle'].every(k=>Number.isFinite(c[k]))||c.target<=0||c.reward<0||c.reward>5e6)throw Error('任務資料損毀')}
for(const f of s.fleet){f.purchasePrice=Number.isFinite(f.purchasePrice)&&f.purchasePrice>0&&f.purchasePrice<=model(f.model).price?f.purchasePrice:model(f.model).price;f.cabin=cabins.some(c=>c.id===f.cabin)?f.cabin:'standard';f.lease=f.lease===true;f.age=Math.floor(bounded(f.age,0,1e8));}
for(const r of s.routes){r.frequency=Number.isInteger(r.frequency)?bounded(r.frequency,0,12):0;r.catering=catering.some(c=>c.id===r.catering)?r.catering:'basic';}
return s}
export function hubSlots(s,code){return (s.hubLimits[code]||10)+(s.facilities[code]?.terminal||0)*8}
export function marketClimate(s,to){const index=airports.findIndex(a=>a.code===to);return {demand:1+.12*Math.sin((s.day+index*11)/18),competition:.94+.06*Math.sin((s.day+index*7)/31),season:Math.sin((s.day+index*11)/18)>.25?'旺季':Math.sin((s.day+index*11)/18)<-.25?'淡季':'平季'}}
export function operations(s,r,m){const f=s.fleet.find(p=>p.id===r.plane),c=cabins.find(c=>c.id===f?.cabin)||cabins[0],service=catering.find(c=>c.id===r.catering)||catering[0],climate=marketClimate(s,r.to);return {capacity:m.cargo?0:Math.floor(m.seats*c.capacity),fare:c.fare,demand:c.demand*service.demand*(1+s.loyalty*.025)*(1+(s.facilities[r.from]?.lounge||0)*.04)*(s.campaign?1.15:1)*climate.demand*climate.competition,cateringCost:service.cost,cargoDemand:1+(s.facilities[r.from]?.cargo||0)*.1,fuelPrice:s.hedge?.price||s.fuelPrice}}
export function usedMarket(s){const cycle=Math.floor(s.day/7),ids=['atr','e195','b738','a321','b789','a359','b77w'];return Array.from({length:5},(_,i)=>{const m=model(ids[(cycle*3+i)%ids.length]);const condition=58+((cycle*13+i*17)%30),id=cycle+'-'+i;return {id,model:m.id,condition,price:Math.round(m.price*(.42+condition*.002)),sold:s.usedBought.includes(id)}})}
export function resaleValue(f){return Math.round(Math.min(model(f.model).price*.65*(.6+f.condition*.004),(f.purchasePrice||model(f.model).price)*.9))}
export function leaseDaily(f){return f.lease?Math.round(model(f.model).price*.0012):0}
export function expansionCosts(s){return {lease:s.fleet.reduce((n,f)=>n+leaseDaily(f),0),facilities:s.hubs.length>1?(s.hubs.length-1)*3500:0,insurance:s.insurance?s.fleet.length*950:0}}
const spend=(s,n)=>{if(n>0&&s.cash<n)throw Error('資金不足');s.cash-=n};const log=(s,text)=>{s.log.unshift({day:s.day,message:text});s.log=s.log.slice(0,35)};
export function commandExpansion(s,type,p,level){switch(type){
case 'open-hub':{if(!airport(p.hub)||s.hubs.includes(p.hub)||s.hubs.length>=6)throw Error('基地已存在或已達 6 座上限');if(level<3)throw Error('Level 3 解鎖第二基地');spend(s,1500000);s.hubs.push(p.hub);s.hubLimits[p.hub]=10;s.facilities[p.hub]=defaults(p.hub).facilities[p.hub];log(s,`成立 ${p.hub} 第二基地`);return true}
case 'facility':{const f=facilities.find(x=>x.id===p.id);if(!f||!s.hubs.includes(p.hub)||s.facilities[p.hub][f.id]>=3)throw Error('設施已滿級或基地不存在');spend(s,f.cost*(s.facilities[p.hub][f.id]+1)**2);s.facilities[p.hub][f.id]++;s.xp+=60;log(s,`${p.hub} ${f.name}升級`);return true}
case 'lease':case 'used-buy':{let m,condition=100,price;if(s.fleet.length>=60)throw Error('機隊已達上限');if(type==='lease'){m=model(p.model);price=m?.price*.12}else{const deal=usedMarket(s).find(d=>d.id===p.id);if(!deal||deal.sold)throw Error('中古飛機已售出或清單已更新');m=model(deal.model);condition=deal.condition;price=deal.price}if(!m||level<m.level)throw Error('機型尚未解鎖');spend(s,Math.round(price));s.fleet.push({id:s.nextId++,model:m.id,condition,cabin:'standard',lease:type==='lease',purchasePrice:Math.round(price),age:type==='used-buy'?200:0});if(type==='used-buy')s.usedBought.push(p.id);log(s,`${type==='lease'?'租入':'購入中古'} ${m.name}`);return true}
case 'return-lease':{const f=s.fleet.find(f=>f.id===Number(p.id));if(!f?.lease||s.routes.some(r=>r.plane===f.id))throw Error('請先關閉租機航線');spend(s,Math.round(model(f.model).price*.02));s.fleet=s.fleet.filter(p=>p.id!==f.id);log(s,'租賃飛機已返還，結清 2% 整備費');return true}
case 'cabin':{const f=s.fleet.find(f=>f.id===Number(p.id)),c=cabins.find(c=>c.id===p.cabin);if(!f||!c||model(f.model).cargo||c.id===f.cabin)throw Error('客艙設定無效');spend(s,Math.round(model(f.model).price*(c.cost||.01)));f.cabin=c.id;log(s,`${model(f.model).name} 改裝${c.name}`);return true}
case 'schedule':{const r=s.routes.find(r=>r.id===Number(p.id));const frequency=Number(p.frequency);if(!r||!Number.isInteger(frequency)||frequency<0||frequency>12||!catering.some(c=>c.id===p.catering))throw Error('班表設定無效');r.frequency=frequency;r.catering=p.catering;return true}
case 'swap-plane':{const r=s.routes.find(r=>r.id===Number(p.id)),f=s.fleet.find(f=>f.id===Number(p.plane));if(!r||!f||s.routes.some(x=>x.plane===f.id&&x.id!==r.id)||p.km>model(f.model).range)throw Error('機型無法執飛此航線');r.plane=f.id;return true}
case 'loyalty':case 'ancillary':{if(s[type]>=5)throw Error('已達最高等級');spend(s,(type==='loyalty'?250000:180000)*(s[type]+1)**2);s[type]++;s.xp+=40;return true}
case 'cargo-enable':if(s.cargo)throw Error('腹艙貨運已啟用');spend(s,80000);s.cargo=1;return true;
case 'campaign':if(s.campaign)throw Error('宣傳活動進行中');spend(s,75000);s.campaign={until:s.day+7};return true;
case 'hedge':if(s.hedge)throw Error('避險合約進行中');spend(s,200000);s.hedge={price:s.fuelPrice,until:s.day+20};return true;
case 'auto-maintain':s.autoMaintain=!s.autoMaintain;return true;
case 'insurance':s.insurance=!s.insurance;return true;
case 'challenge-claim':{const c=s.challenge;if(!c||(c.metric==='cargo'?s.totalCargo:s[c.metric])-c.start<c.target||s.day>c.until)throw Error('任務尚未達成或已到期');s.cash+=c.reward;s.xp+=120;s.rep=Math.min(100,s.rep+1);s.challenge=null;log(s,'企業委託完成，獎勵已入帳');return true}
case 'achievement':{const a=achievements.find(a=>a.id===p.id);if(!a||s.achievements.includes(a.id)||a.value(s)<a.target)throw Error('成就尚未完成');s.achievements.push(a.id);s.cash+=a.reward;s.xp+=150;log(s,`取得成就：${a.name}`);return true}
case 'branding':if(!String(p.name||'').trim()||!/^[A-Z0-9]{2,3}$/.test(p.code)||!/^#[0-9a-f]{6}$/i.test(p.color))throw Error('公司資料格式無效');s.name=p.name.trim().slice(0,28);s.code=p.code;s.color=p.color;return true;
default:return false}}
export const achievements=[{id:'hub2',name:'雙城航空',target:2,value:s=>s.hubs.length,reward:600000},{id:'cargo1000',name:'貨運先鋒',target:1000,value:s=>s.totalCargo,reward:700000},{id:'routes10',name:'區域霸主',target:10,value:s=>s.routes.length,reward:1500000},{id:'fleet20',name:'機隊帝國',target:20,value:s=>s.fleet.length,reward:5000000},{id:'loyal5',name:'旅客忠誠',target:5,value:s=>s.loyalty,reward:1000000},{id:'training5',name:'卓越團隊',target:5,value:s=>s.training,reward:600000},{id:'rep95',name:'五星品牌',target:95,value:s=>s.rep,reward:1200000},{id:'millionRevenue',name:'營收里程碑',target:100000000,value:s=>s.totalRevenue,reward:3000000}];
export function expansionDay(s,rng){let maintenance=0;if(s.effect&&s.day>s.effect.until)s.effect=null;if(s.campaign&&s.day>s.campaign.until)s.campaign=null;if(s.hedge&&s.day>s.hedge.until)s.hedge=null;s.fuelPrice=Math.min(1.6,Math.max(.65,s.fuelPrice+(rng(s)-.5)*.06));for(const f of s.fleet){f.age++;if(s.autoMaintain&&f.condition<35){const bill=Math.ceil((100-f.condition)*model(f.model).price*.00015);if(s.cash-maintenance>=bill){maintenance+=bill;f.condition=100;log(s,`${model(f.model).name} 自動維護 ${bill.toLocaleString()}`)}}}
if(s.event&&s.event.type!=='incident'&&s.day%5===0)s.event=null;
if(s.challenge&&s.day>s.challenge.until){s.news.unshift({day:s.day,text:'企業委託已到期，下一輪重新招標'});s.challenge=null}
if(s.day%7===0&&!s.challenge){const metric=['pax','flights','cargo'][s.challengeCycle%3];s.challengeCycle++;const target=metric==='pax'?6000+s.challengeCycle*1000:metric==='flights'?30+s.challengeCycle*3:120+s.challengeCycle*20;s.challenge={metric,target,start:metric==='cargo'?s.totalCargo:s[metric],reward:Math.min(5000000,250000+s.challengeCycle*75000),until:s.day+21,cycle:s.challengeCycle};s.news.unshift({day:s.day,text:'新企業委託已開放：'+({pax:'旅客運輸',flights:'航班營運',cargo:'貨物運送'}[metric])})}
if(s.day%10===0)s.news.unshift({day:s.day,text:s.fuelPrice>1.1?'燃油價格走高：留意避險與省油機型':'全球航空市場更新：評估旺季目的地與競爭壓力'});s.news=s.news.slice(0,12);return maintenance}
