import {airports,airport} from './data.js';
let land=null;fetch('/assets/land.json').then(r=>r.json()).then(x=>land=x).catch(()=>{});
export function mountMap(canvas,getState,onAirport){const ctx=canvas.getContext('2d');let frame=0,closed=false,points=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function draw(t){if(closed||!canvas.isConnected)return;const box=canvas.getBoundingClientRect(),w=box.width,h=box.height;if(!w||!h)return;const dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const s=getState();const project=(lon,lat)=>[(((lon+60)%360+360)%360)/360*w,(78-lat)/140*h];ctx.strokeStyle='#233137';ctx.lineWidth=.7;for(let l=-180;l<=180;l+=30){const x=project(l,0)[0];ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let lat=-60;lat<=60;lat+=30){const y=project(0,lat)[1];ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
if(land){ctx.fillStyle='#26383d';ctx.strokeStyle='#3a4a4e';ctx.lineWidth=.6;for(const f of land.features){const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const poly of polygons){const rings=poly.map(ring=>{let previous=null;return ring.map(([lon,lat])=>{const p=project(lon,lat);if(previous!==null){while(p[0]-previous>w/2)p[0]-=w;while(p[0]-previous< -w/2)p[0]+=w}previous=p[0];return p})});for(const shift of [-w,0,w]){ctx.beginPath();for(const ring of rings){ring.forEach((p,i)=>i?ctx.lineTo(p[0]+shift,p[1]):ctx.moveTo(p[0]+shift,p[1]));ctx.closePath()}ctx.fill('evenodd');ctx.stroke()}}}}

const connected=new Set([s.hub,...s.routes.map(r=>r.to)]);for(const r of s.routes){let a=project(airport(r.from).lon,airport(r.from).lat),b=project(airport(r.to).lon,airport(r.to).lat);if(Math.abs(b[0]-a[0])>w/2)b=[b[0]+(b[0]<a[0]?w:-w),b[1]];const cx=(a[0]+b[0])/2,cy=Math.min(a[1],b[1])-Math.min(70,Math.abs(a[0]-b[0])*.22+20);for(const shift of [-w,0,w]){ctx.strokeStyle=r.active?'#b4d983':'#627579';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(a[0]+shift,a[1]);ctx.quadraticCurveTo(cx+shift,cy,b[0]+shift,b[1]);ctx.stroke();if(r.active){const v=reduced?.5:((t/12000+r.id*.12)%1);const x=(1-v)**2*a[0]+2*(1-v)*v*cx+v*v*b[0]+shift,y=(1-v)**2*a[1]+2*(1-v)*v*cy+v*v*b[1];ctx.fillStyle='#e7f8c1';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()}}}
points=[];for(const a of airports){const [x,y]=project(a.lon,a.lat);points.push({x,y,a});const isHub=a.code===s.hub,isActive=connected.has(a.code);ctx.fillStyle=isHub?'#c6ed89':isActive?'#a8dbea':'#63777c';ctx.beginPath();ctx.arc(x,y,isHub?5:isActive?3.5:2.3,0,Math.PI*2);ctx.fill();if(isHub){ctx.strokeStyle='#c6ed8955';ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.stroke()}if(isActive){ctx.font='11px system-ui';ctx.fillStyle='#e6eeee';ctx.fillText(a.code,x+8,y-6)}}frame=requestAnimationFrame(draw)}
canvas.onclick=e=>{const b=canvas.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top;const p=points.map(p=>({...p,d:Math.hypot(p.x-x,p.y-y)})).sort((a,b)=>a.d-b.d)[0];if(p?.d<20)onAirport(p.a.code)};frame=requestAnimationFrame(draw);return()=>{closed=true;cancelAnimationFrame(frame)}}
